# Generated by Django 5.0.1 on 2024-03-13 22:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_tipodocumentofaena_documento_and_more'),
        ('vehicle', '0010_alter_informaciontecnicavehiculo_capacidadcarga_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechatraspaso', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Traspaso')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('faenaActual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faena', verbose_name='Faena Actual')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Vehiculo en Faena',
                'verbose_name_plural': 'Vehiculos en Faena',
                'db_table': 'mining_vehicles',
            },
        ),
    ]
