# Generated by Django 5.0.1 on 2024-03-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculoasignado',
            old_name='faenaActual',
            new_name='faena',
        ),
        migrations.RenameField(
            model_name='vehiculoasignado',
            old_name='fechatraspaso',
            new_name='fechaFinal',
        ),
        migrations.AddField(
            model_name='vehiculoasignado',
            name='creador',
            field=models.CharField(max_length=50, null=True, verbose_name='Creador'),
        ),
        migrations.AddField(
            model_name='vehiculoasignado',
            name='fechaInicial',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Traspaso'),
        ),
    ]
