# Generated by Django 5.0.1 on 2024-03-14 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tipodocumentofaena_documento_and_more'),
        ('mining', '0002_rename_faenaactual_vehiculoasignado_faena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculoasignado',
            name='faenaActual',
            field=models.CharField(max_length=50, null=True, verbose_name='Faena Actual'),
        ),
        migrations.AlterField(
            model_name='vehiculoasignado',
            name='faena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faena', verbose_name='Faena Siguiente'),
        ),
        migrations.AlterField(
            model_name='vehiculoasignado',
            name='fechaFinal',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Final Traspaso'),
        ),
        migrations.AlterField(
            model_name='vehiculoasignado',
            name='fechaInicial',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha inicial Traspaso'),
        ),
    ]
