# Generated by Django 5.0.1 on 2024-03-14 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tipodocumentofaena_documento_and_more'),
        ('mining', '0003_vehiculoasignado_faenaactual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculoasignado',
            name='faenaActual',
        ),
        migrations.AddField(
            model_name='vehiculoasignado',
            name='faenaAnterior',
            field=models.CharField(max_length=50, null=True, verbose_name='Faena Anterior'),
        ),
        migrations.AlterField(
            model_name='vehiculoasignado',
            name='faena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faena', verbose_name='Faena Actual'),
        ),
    ]
