# Generated by Django 5.0.1 on 2024-03-20 04:29

import django.utils.timezone
import mining.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0004_remove_vehiculoasignado_faenaactual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPorFaena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faena', models.CharField(max_length=100, null=True, verbose_name='Faena')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('documento', models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=mining.models.DocumentoPorFaena.generaNombre)),
            ],
            options={
                'verbose_name': 'Documento por Faena',
                'verbose_name_plural': 'Documentos por Faena',
                'db_table': 'mining_documents',
            },
        ),
    ]
