# Generated by Django 5.0.1 on 2024-03-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0005_documentoporfaena'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoporfaena',
            name='patente',
            field=models.CharField(max_length=50, null=True, verbose_name='Patente'),
        ),
    ]
