# Generated by Django 5.0.1 on 2024-03-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0006_documentoporfaena_patente'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoporfaena',
            name='tipoDocumento',
            field=models.CharField(max_length=100, null=True, verbose_name='Tipo Documento'),
        ),
    ]
