# Generated by Django 5.0.1 on 2024-03-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0007_documentoporfaena_tipodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoporfaena',
            name='fechaVencimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Vencimiento'),
        ),
    ]
