# Generated by Django 5.0.1 on 2024-03-13 06:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_faena'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoFaena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=100, verbose_name='Descripción Faena')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('faena', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.faena')),
            ],
            options={
                'verbose_name': 'Tipo Documento Faena',
                'verbose_name_plural': 'Tipos Documentos Faena',
                'db_table': 'mining_document_type',
            },
        ),
    ]
