# Generated by Django 5.0.1 on 2024-03-13 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tipodocumentofaena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumentofaena',
            name='documento',
            field=models.CharField(max_length=100, verbose_name='Tipo Documento Faena'),
        ),
        migrations.AlterField(
            model_name='tipodocumentofaena',
            name='faena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faena'),
        ),
    ]
