# Generated by Django 5.0.1 on 2024-03-19 03:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tipodocumentofaena_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=25, unique=True, verbose_name='Nombre Empresa')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('direccion', models.CharField(max_length=500, verbose_name='Dirección ')),
                ('rut', models.CharField(max_length=50, verbose_name='Rut')),
                ('telefono', models.IntegerField(null=True, verbose_name='Telefono')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Empresa de Mantenimiento',
                'verbose_name_plural': 'Empresas de Mantenimiento',
                'db_table': 'companies_profile',
            },
        ),
        migrations.CreateModel(
            name='EmpresaTipoServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresaservicios')),
            ],
            options={
                'verbose_name': 'Servicio de Mantenimiento',
                'verbose_name_plural': 'Servicios de Mantenimientos',
                'db_table': 'companies_maintenance_services',
            },
        ),
    ]
