# Generated by Django 5.0.1 on 2024-03-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresaservicios_empresatiposervicios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresatiposervicios',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='empresatiposervicios',
            name='servicio',
            field=models.CharField(max_length=100, null=True, verbose_name='Descripción'),
        ),
    ]
