# Generated by Django 5.0.1 on 2024-03-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_empresatiposervicios_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresatiposervicios',
            name='servicio',
            field=models.CharField(max_length=100, null=True, verbose_name='Tipo de Servicio'),
        ),
    ]
