# Generated by Django 5.0.1 on 2024-03-22 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_empresatiposervicios_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFallaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falla', models.CharField(max_length=200, null=True, verbose_name='Tipo de Falla')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tipo de Falla',
                'verbose_name_plural': 'Tipos de Fallas',
                'db_table': 'vehicle_failure',
            },
        ),
    ]
