# Generated by Django 5.0.1 on 2024-03-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tipofallavehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ano',
            name='ano',
            field=models.CharField(max_length=50, unique=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=50, unique=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='empresaservicios',
            name='empresa',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre Empresa'),
        ),
        migrations.AlterField(
            model_name='faena',
            name='faena',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre Faena'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='genero',
            field=models.CharField(max_length=50, unique=True, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='marca',
            field=models.CharField(max_length=50, unique=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='modelo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='nacionalidad',
            name='nacionalidad',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='tipo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tipo'),
        ),
    ]
