# Generated by Django 5.0.1 on 2024-03-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_ano_ano_alter_color_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcultarOpcionesVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placaPatente', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Patente (Requerido)')),
                ('rutPropietario', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Rut Propietario (Reqquerido)')),
                ('fechaAdquisicion', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Fecha Adquisición (Requerido)')),
                ('nombrePropietario', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Nombre Propietario (Requerido)')),
                ('domicilio', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Domicilio (Requerido)')),
                ('tipo', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Tipo Vehículo (Requerido)')),
                ('marca', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Marca Vehículo (Requerido)')),
                ('modelo', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Modelo Vehículo (Requerido)')),
                ('ano', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Año Vehículo (Requerido)')),
                ('numeroMotor', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='N° Motor (Requerido)')),
                ('numeroChasis', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='N° Chasis (Requerido)')),
                ('numeroVin', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name=' N° Vin (Requerido)')),
                ('color', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Color Vehículo (Requerido)')),
                ('fechaVencimientoPermisoCirculacion', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Vencimiento Permiso Circulación (Requerido)')),
                ('fechaVencimientoRevisionTecnica', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Vencimiento Revisión Técnica (Requerido)')),
                ('fechaVencimientoSeguroObligatorio', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Vencimiento Seguro Obligatorio (Requerido)')),
                ('fechaVencimientoLamina', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Vencimiento Lámina (Opcional)')),
                ('fechaInstalacionBarraAntiVuelco', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Vencimiento Barra AntiVuelco (Opcional)')),
                ('fechaInstalacionGps', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Instalación Gps (Opcional)')),
                ('fechaVencimientoTransportePrivado', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Vencimiento Transporte Privado (Opcional)')),
                ('tieneTag', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Tiene Tag (Opcional)')),
                ('tipoTraccion', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Tipo Tracción')),
                ('pesoBrutoVehicular', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Peso Bruto Vehicular')),
                ('capacidadCarga', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Capacidad de Carga')),
                ('tipoNeumatico', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Tipo Neumático')),
                ('tipoAceiteMotor', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Tipo Aceite Motor')),
                ('tipoRefrigeranteMotor', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Tipo Refrigerante Motor')),
                ('tipoFiltroAireMotor', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Tipo Filtro Aire Motor')),
                ('tipoFiltroCombustible', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Tipo Filtro Combustible')),
                ('fotografiaFacturaCompra', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Documentación Factura de Compra')),
                ('fotografiaPadron', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Documentación Padrón')),
                ('fotografiaPermisoCirculacion', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Documentación ')),
                ('fotografiaRevisionTecnica', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Documentación Revision Técnica')),
                ('fotografiaRevisionTecnicaGases', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Documentación Revision Técnica Gases')),
                ('fotografiaSeguroObligatorio', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Documentación Seguro Obligatorio')),
                ('fotografiaSeguroAutomotriz', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Documentación Seguro Automotriz')),
                ('fotografiaCertificadoGps', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Certificado Gps')),
                ('fotografiaCertificadoLamina', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Certificado Lámina')),
                ('fotografiaCertificadoBarraAntiVuelco', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Certificado Barra AntiVuelco')),
                ('fotografiaDocumentacionMiniBus', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Documentación Documentacion MiniBús')),
                ('fotografiaInteriorTablero', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Fotografía Interior Tablero')),
                ('fotografiaInteriorCopiloto', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Fotografía Interior Copiloto')),
                ('fotografiaInteriorAtrasPiloto', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Fotografía Interior Atrás Piloto ')),
                ('fotografiaInteriorAtrasCopiloto', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Fotografía Interior Atrás Copiloto ')),
                ('fotografiaExteriorFrontis', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Fotografía Exterior Frontis')),
                ('fotografiaExteriorAtras', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Fotografía Exterior Atrás')),
                ('fotografiaExteriorPiloto', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Fotografía Exterior Lado Piloto')),
                ('fotografiaExteriorCopiloto', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=10, null=True, verbose_name='Fotografía Exterior Lado Copiloto')),
            ],
            options={
                'verbose_name': 'Ocultar Información de Vehiculo',
                'verbose_name_plural': 'Ocultar Información de Vehiculo',
                'db_table': 'vehicle_hide_options',
            },
        ),
    ]
