# Generated by Django 5.0.1 on 2024-03-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ocultaropcionesvehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocultaropcionesvehiculo',
            name='tipo_vehiculo',
            field=models.CharField(max_length=100, null=True, verbose_name='Tipo de Vehículo'),
        ),
    ]
