# Generated by Django 5.0.1 on 2024-03-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ocultaropcionesvehiculo_tipo_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='ano',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Año Vehículo (Requerido)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='capacidadCarga',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Capacidad de Carga'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='color',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Color Vehículo (Requerido)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='domicilio',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Domicilio (Requerido)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fechaAdquisicion',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Fecha Adquisición (Requerido)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fechaInstalacionBarraAntiVuelco',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Vencimiento Barra AntiVuelco (Opcional)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fechaInstalacionGps',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Instalación Gps (Opcional)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fechaVencimientoLamina',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Vencimiento Lámina (Opcional)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fechaVencimientoPermisoCirculacion',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Vencimiento Permiso Circulación (Requerido)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fechaVencimientoRevisionTecnica',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Vencimiento Revisión Técnica (Requerido)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fechaVencimientoSeguroObligatorio',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Vencimiento Seguro Obligatorio (Requerido)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fechaVencimientoTransportePrivado',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Vencimiento Transporte Privado (Opcional)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaCertificadoBarraAntiVuelco',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Certificado Barra AntiVuelco'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaCertificadoGps',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Certificado Gps'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaCertificadoLamina',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Certificado Lámina'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaDocumentacionMiniBus',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Documentación Documentacion MiniBús'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaExteriorAtras',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Fotografía Exterior Atrás'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaExteriorCopiloto',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Fotografía Exterior Lado Copiloto'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaExteriorFrontis',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Fotografía Exterior Frontis'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaExteriorPiloto',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Fotografía Exterior Lado Piloto'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaFacturaCompra',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Documentación Factura de Compra'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaInteriorAtrasCopiloto',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Fotografía Interior Atrás Copiloto '),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaInteriorAtrasPiloto',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Fotografía Interior Atrás Piloto '),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaInteriorCopiloto',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Fotografía Interior Copiloto'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaInteriorTablero',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Fotografía Interior Tablero'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaPadron',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Documentación Padrón'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaPermisoCirculacion',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Documentación '),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaRevisionTecnica',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Documentación Revision Técnica'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaRevisionTecnicaGases',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Documentación Revision Técnica Gases'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaSeguroAutomotriz',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Documentación Seguro Automotriz'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaSeguroObligatorio',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Documentación Seguro Obligatorio'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='marca',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Marca Vehículo (Requerido)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='modelo',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Modelo Vehículo (Requerido)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='nombrePropietario',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Nombre Propietario (Requerido)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='numeroChasis',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='N° Chasis (Requerido)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='numeroMotor',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='N° Motor (Requerido)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='numeroVin',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name=' N° Vin (Requerido)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='pesoBrutoVehicular',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Peso Bruto Vehicular'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='placaPatente',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Patente (Requerido)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='rutPropietario',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Rut Propietario (Reqquerido)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='tieneTag',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Tiene Tag (Opcional)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='tipo',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Tipo Vehículo (Requerido)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='tipoAceiteMotor',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Tipo Aceite Motor'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='tipoFiltroAireMotor',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Tipo Filtro Aire Motor'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='tipoFiltroCombustible',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Tipo Filtro Combustible'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='tipoNeumatico',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Tipo Neumático'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='tipoRefrigeranteMotor',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Tipo Refrigerante Motor'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='tipoTraccion',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Tipo Tracción'),
        ),
    ]
