# Generated by Django 5.0.1 on 2024-04-03 20:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_ocultaropcionesvehiculo_ano_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFallaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=200, null=True, verbose_name='Categoría de Falla')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tipo Categoría de Falla',
                'verbose_name_plural': 'Tipos Categorías de Fallas',
                'db_table': 'vehicle_categories_failure',
            },
        ),
        migrations.AddField(
            model_name='tipofallavehiculo',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoriafallavehiculo'),
        ),
    ]
