# Generated by Django 5.0.1 on 2024-04-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_categoriafallavehiculo_tipofallavehiculo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriafallavehiculo',
            name='categoria',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Categoría de Falla'),
        ),
    ]
