# Generated by Django 5.0.1 on 2024-04-24 21:38

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_categoriafallavehiculo_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoFaenaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('documento', models.ImageField(blank=True, default='base/no-imagen.png', null=True, upload_to=core.models.TipoDocumentoFaenaGeneral.generaNombre)),
                ('faena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faena')),
            ],
            options={
                'verbose_name': 'Tipo Documento Faena',
                'verbose_name_plural': 'Tipos Documentos Faena',
                'db_table': 'mining_document_type_general',
            },
        ),
    ]
