# Generated by Django 5.0.1 on 2024-04-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tipodocumentofaenageneral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipodocumentofaenageneral',
            old_name='documento',
            new_name='archivodocumento',
        ),
        migrations.AddField(
            model_name='tipodocumentofaenageneral',
            name='nombredocumento',
            field=models.CharField(max_length=100, null=True, verbose_name='Tipo Documento Faena'),
        ),
    ]
