# Generated by Django 5.0.1 on 2024-04-27 01:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_documento_tipodocumentofaenageneral_archivodocumento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitsMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreKit', models.CharField(max_length=50, unique=True, verbose_name='Kit de Reparación')),
                ('stockMinimo', models.IntegerField(null=True, verbose_name='Stock Minimo')),
                ('stockMaximo', models.IntegerField(null=True, verbose_name='Stock Máximo')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Marca o Modelo',
                'verbose_name_plural': 'Marca o Modelos',
                'db_table': 'machine_kit_machine',
            },
        ),
        migrations.CreateModel(
            name='MarcaMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, unique=True, verbose_name='Marca o Modelo')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Marca o Modelo',
                'verbose_name_plural': 'Marca o Modelos',
                'db_table': 'machine_model',
            },
        ),
        migrations.CreateModel(
            name='TipoMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, unique=True, verbose_name='Tipo Máquina')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'db_table': 'machine_type',
            },
        ),
        migrations.CreateModel(
            name='FallaMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falla', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Falla')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('kitMaquinaina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.kitsmaquinaria')),
            ],
            options={
                'verbose_name': 'Falla en Máquina',
                'verbose_name_plural': 'Fallas en Máquinas',
                'db_table': 'machine_failure',
            },
        ),
        migrations.AddField(
            model_name='kitsmaquinaria',
            name='marcaMaquina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.marcamaquinaria'),
        ),
        migrations.AddField(
            model_name='marcamaquinaria',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipomaquinaria'),
        ),
    ]
