# Generated by Django 5.0.1 on 2024-04-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_kitsmaquinaria_marcamaquinaria_tipomaquinaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallamaquinaria',
            name='falla',
            field=models.CharField(max_length=50, verbose_name='Tipo de Falla'),
        ),
        migrations.AlterField(
            model_name='kitsmaquinaria',
            name='nombreKit',
            field=models.CharField(max_length=50, verbose_name='Kit de Reparación'),
        ),
        migrations.AlterField(
            model_name='marcamaquinaria',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='Marca o Modelo'),
        ),
        migrations.AlterField(
            model_name='tipomaquinaria',
            name='tipo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tipo Máquinaria'),
        ),
    ]
