# Generated by Django 5.0.1 on 2024-04-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_fallamaquinaria_falla_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fallamaquinaria',
            old_name='kitMaquinaina',
            new_name='kitMaquinaria',
        ),
    ]
