# Generated by Django 5.0.1 on 2024-05-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_kitmaquinaina_fallamaquinaria_kitmaquinaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaPermisoCirculacion',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Documentación Permiso Circulación'),
        ),
    ]
