# Generated by Django 5.0.1 on 2024-05-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_ocultaropcionesvehiculo_fotografiapermisocirculacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaDocumentacionMiniBus',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Documentacion MiniBús'),
        ),
    ]
