# Generated by Django 5.0.1 on 2024-05-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ocultaropcionesvehiculo_frecuenciamantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='frecuenciaMantenimiento',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Frecuencia de Mantenimiento (Kilometros)'),
        ),
    ]
