# Generated by Django 5.0.1 on 2024-05-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_ocultaropcionesvehiculo_frecuenciamantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocultaropcionesvehiculo',
            name='fechaCertificadoGrua',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Fecha Certificado Grua'),
        ),
        migrations.AddField(
            model_name='ocultaropcionesvehiculo',
            name='fechaCertificadoMantencion',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Fecha Certificado Mantenimiento'),
        ),
        migrations.AddField(
            model_name='ocultaropcionesvehiculo',
            name='fechaCertificadoOperatividad',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Fecha Certificado Operatividad'),
        ),
        migrations.AddField(
            model_name='ocultaropcionesvehiculo',
            name='proximoMantenimiento',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Proximo Mantenimiento'),
        ),
        migrations.AddField(
            model_name='ocultaropcionesvehiculo',
            name='proximoMantenimientoGrua',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Proximo Mantenimiento Grua'),
        ),
    ]
