# Generated by Django 5.0.1 on 2024-05-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_ocultaropcionesvehiculo_fechacertificadogrua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaCertificadoGrua',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Certificado Grua'),
        ),
        migrations.AddField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaCertificadoMantencion',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Certificado Mantenimiento'),
        ),
        migrations.AddField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaCertificadoOperatividad',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Certificado Operatividad'),
        ),
    ]
