# Generated by Django 5.0.1 on 2024-05-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_ocultaropcionesvehiculo_fotografiacertificadogrua_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaDocumentacionMiniBus',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Documentación Transp. Privado'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='proximoMantenimiento',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Proximo Mantenimiento (Kilometros)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='proximoMantenimientoGrua',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Proximo Mantenimiento Grua (Horómetro)'),
        ),
    ]
