# Generated by Django 5.0.1 on 2024-06-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_ocultaropcionesvehiculo_fotografiadocumentacionminibus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaCertificadoBarraAntiVuelco',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Certificado de Barra AntiVuelco'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaCertificadoGps',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Certificado GPS'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaCertificadoGrua',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Certificado Grúa'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaCertificadoLamina',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Certificado de Lámina'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaCertificadoMantencion',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Certificado de Mantención'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaCertificadoOperatividad',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Certificado de Operatividad'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaExteriorCopiloto',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Fotografía Exterior Lado Acompañante'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaExteriorPiloto',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Fotografía Exterior Lado Conductor'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaFacturaCompra',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Factura de Compra'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaInteriorAtrasCopiloto',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Fotografía Interior Atrás Acompanante'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaInteriorAtrasPiloto',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Fotografía Interior Atrás Conductor'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaInteriorCopiloto',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Fotografía Interior Acompañante'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaPadron',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Padrón Vehicular'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaPermisoCirculacion',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Permiso Circulación'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaRevisionTecnica',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Revisión Técnica'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaRevisionTecnicaGases',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Revisión Técnica de Gases'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaSeguroAutomotriz',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Seguro Automotriz'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fotografiaSeguroObligatorio',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Seguro Obligatorio'),
        ),
    ]
