# Generated by Django 5.0.1 on 2024-06-04 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_ocultaropcionesvehiculo_fotografiacertificadobarraantivuelco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechasImportantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción Fecha')),
                ('fechaVencimiento', models.DateTimeField(null=True, verbose_name='Mes de Vencimiento')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Fecha Importante',
                'verbose_name_plural': 'Fechas Importantes',
                'db_table': 'vehicle_important_dates',
            },
        ),
    ]
