# Generated by Django 5.0.1 on 2024-06-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_fechasimportantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechasimportantes',
            name='fechaVencimiento',
            field=models.CharField(choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=20, null=True, verbose_name='Mes de Vencimiento'),
        ),
    ]
