# Generated by Django 5.0.1 on 2024-07-25 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_fechasimportantes_fechavencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Usuario')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('detalle', models.CharField(max_length=500, verbose_name='Detalle del Error')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Reporte de Error',
                'verbose_name_plural': 'Reporte de Errores',
                'db_table': 'report_errors',
            },
        ),
    ]
