# Generated by Django 5.0.1 on 2024-07-25 07:59

import core.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_reporteerror'),
    ]

    operations = [
        migrations.CreateModel(
            name='AyudaManuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('1', 'Registro Vehicular'), ('2', 'Registro Maquinarias'), ('3', 'Planificación'), ('4', 'Documentación'), ('5', 'Estadísticas'), ('6', 'Usuarios'), ('7', 'Mantenedor de Sistema'), ('8', 'Reporte de Errores'), ('9', 'Perfil Usuario'), ('10', 'DashBoard')], max_length=100, verbose_name='Secció')),
                ('nombredocumento', models.CharField(max_length=100, null=True, verbose_name='Nombre Documento')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('archivodocumento', models.ImageField(blank=True, default='base/no-imagen.png', null=True, upload_to=core.models.AyudaManuales.generaNombre)),
            ],
            options={
                'verbose_name': 'Documento Ayuda y Manual ',
                'verbose_name_plural': 'Documentos Ayuda y Manuales',
                'db_table': 'documents_help_manuals',
            },
        ),
    ]
