# Generated by Django 5.0.1 on 2024-07-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_ayudamanuales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayudamanuales',
            name='seccion',
            field=models.CharField(choices=[('1', 'Registro Vehicular'), ('2', 'Registro Maquinarias'), ('3', 'Planificación'), ('4', 'Documentación'), ('5', 'Estadísticas'), ('6', 'Usuarios'), ('7', 'Mantenedor de Sistema'), ('8', 'Reporte de Errores'), ('9', 'Perfil Usuario'), ('10', 'DashBoard')], max_length=100, verbose_name='Sección'),
        ),
    ]
