# Generated by Django 5.0.1 on 2024-09-11 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_ayudamanuales_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aditivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aditivo', models.CharField(max_length=100, null=True, verbose_name='Aditivo')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Aditivo',
                'verbose_name_plural': 'Aditivos',
                'db_table': 'drilling_aditivos',
            },
        ),
        migrations.CreateModel(
            name='CantidadAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadAgua', models.IntegerField(null=True, verbose_name='Litros Agua')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Litros Agua',
                'verbose_name_plural': 'Litros Agua',
                'db_table': 'drilling_cant_water',
            },
        ),
        migrations.CreateModel(
            name='Casing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casing', models.CharField(max_length=100, null=True, verbose_name='Casing')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Casing',
                'verbose_name_plural': 'Casing',
                'db_table': 'drilling_casing',
            },
        ),
        migrations.CreateModel(
            name='Corona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corona', models.CharField(max_length=100, null=True, verbose_name='Corona')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Corona',
                'verbose_name_plural': 'Coronas',
                'db_table': 'drilling_corona',
            },
        ),
        migrations.CreateModel(
            name='DetalleControlHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=100, null=True, verbose_name='Detalle')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Detalle Control Horario',
                'verbose_name_plural': 'Detalles Control Horario',
                'db_table': 'drilling_details',
            },
        ),
        migrations.CreateModel(
            name='Diametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diametro', models.CharField(max_length=100, null=True, verbose_name='Diametro')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Diametro',
                'verbose_name_plural': 'Diametros',
                'db_table': 'drilling_diameter',
            },
        ),
        migrations.CreateModel(
            name='Escareador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escareador', models.CharField(max_length=100, null=True, verbose_name='Escareador')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Escareador',
                'verbose_name_plural': 'Escareadores',
                'db_table': 'drilling_escareador',
            },
        ),
        migrations.CreateModel(
            name='LargoBarra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largoBarra', models.IntegerField(null=True, verbose_name='Largo Barra (Mts)')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Largo Barra',
                'verbose_name_plural': 'Largo Barras',
                'db_table': 'drilling_largo_barra',
            },
        ),
        migrations.CreateModel(
            name='Orientacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientacion', models.CharField(max_length=100, null=True, verbose_name='Orientacion')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Orientacion',
                'verbose_name_plural': 'Orientaciones',
                'db_table': 'drilling_orientation',
            },
        ),
        migrations.CreateModel(
            name='Perforistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perforista', models.CharField(max_length=100, null=True, verbose_name='Perforista')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Perforista',
                'verbose_name_plural': 'Perforistas',
                'db_table': 'drilling_perforista',
            },
        ),
        migrations.CreateModel(
            name='Sondajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sondaje', models.CharField(max_length=100, null=True, verbose_name='Sondajes')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Sondaje Minero',
                'verbose_name_plural': 'Sondajes Mineros',
                'db_table': 'drilling_drilling',
            },
        ),
        migrations.CreateModel(
            name='Sondas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sonda', models.CharField(max_length=100, null=True, verbose_name='Sonda')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Sonda Minera',
                'verbose_name_plural': 'Sondas Mineras',
                'db_table': 'drilling_probe',
            },
        ),
        migrations.CreateModel(
            name='TipoTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoTerreno', models.CharField(max_length=100, null=True, verbose_name='Tipo Terreno')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tipo Terreno',
                'verbose_name_plural': 'Tipo Terrenos',
                'db_table': 'drilling_land_type',
            },
        ),
        migrations.CreateModel(
            name='Zapata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zapata', models.CharField(max_length=100, null=True, verbose_name='Zapata')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Zapata',
                'verbose_name_plural': 'Zapatas',
                'db_table': 'drilling_zapata',
            },
        ),
    ]
