# Generated by Django 5.1.1 on 2024-10-04 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_aditivos_cantidadagua_casing_corona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sondajes',
            name='faena',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faena'),
        ),
    ]
