# Generated by Django 5.1.1 on 2024-11-13 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_materialescaseta_materialessonda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialescaseta',
            options={'verbose_name': 'Material Caseta', 'verbose_name_plural': 'Materiales Caseta'},
        ),
        migrations.AlterModelOptions(
            name='materialessonda',
            options={'verbose_name': 'Material Sonda', 'verbose_name_plural': 'Materiales Sonda'},
        ),
    ]
