# Generated by Django 5.1.1 on 2024-11-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_materialescaseta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sondajes',
            name='sondaje',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Sondajes'),
        ),
    ]
