# Generated by Django 5.1.1 on 2025-01-21 18:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_sondajes_sondaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendacion', models.CharField(max_length=50, null=True, verbose_name='Recomendacion')),
                ('pozo', models.CharField(max_length=50, null=True, verbose_name='Pozo')),
                ('sonda', models.CharField(max_length=50, null=True, verbose_name='Sonda')),
                ('fecha_inicio', models.DateField(null=True, verbose_name='Fecha de Inicio')),
                ('sector', models.CharField(max_length=50, null=True, verbose_name='Sector')),
                ('azimut', models.IntegerField(null=True, verbose_name='Azimut')),
                ('inclinacion', models.IntegerField(null=True, verbose_name='Inclinacion')),
                ('largo_programado', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Largo Programado')),
                ('largo_real', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Largo Real')),
                ('este', models.IntegerField(null=True, verbose_name='Este')),
                ('norte', models.IntegerField(null=True, verbose_name='Norte')),
                ('cota', models.IntegerField(null=True, verbose_name='Cota')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Recomendacion',
                'verbose_name_plural': 'Recomendaciones',
                'db_table': 'drilling_recommendation',
            },
        ),
    ]
