# Generated by Django 5.1.1 on 2025-01-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_recomendacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacion',
            name='fecha_inicio',
            field=models.DateTimeField(null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='inclinacion',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Inclinación'),
        ),
    ]
