# Generated by Django 5.1.1 on 2025-01-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_recomendacion_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacion',
            name='este',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Este'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='norte',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Norte'),
        ),
    ]
