# Generated by Django 5.1.1 on 2025-01-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_recomendacion_este_alter_recomendacion_norte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacion',
            name='cota',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Cota'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='este',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='Este'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='norte',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='Norte'),
        ),
    ]
