# Generated by Django 5.1.1 on 2025-01-24 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_recomendacion_cota_alter_recomendacion_este_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacion',
            name='recomendacion',
            field=models.CharField(max_length=50, null=True, verbose_name='Recomendación'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='sonda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='core.sondas', verbose_name='Sonda'),
        ),
    ]
