# Generated by Django 5.1.1 on 2025-01-28 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_recomendacion_recomendacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacion',
            name='sonda',
            field=models.ForeignKey(help_text='En caso de elegir una sonda diferente, debe crearla previamente.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='core.sondas', verbose_name='Sonda'),
        ),
    ]
