# Generated by Django 5.1.1 on 2025-01-28 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_recomendacion_sonda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacion',
            name='azimut',
            field=models.IntegerField(help_text='Este campo acepta únicamente valores enteros.', null=True, verbose_name='Azimut'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='cota',
            field=models.DecimalField(decimal_places=3, help_text='Este campo acepta valores enteros y decimales. Ejemplo, 12345.678.', max_digits=10, null=True, verbose_name='Cota'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='este',
            field=models.DecimalField(decimal_places=3, help_text='Este campo acepta valores enteros y decimales. Ejemplo, 12345.678.', max_digits=12, null=True, verbose_name='Este'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='fecha_inicio',
            field=models.DateTimeField(help_text='Fecha en que se inicia la actividad asociada.', null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='inclinacion',
            field=models.DecimalField(decimal_places=2, help_text='Este campo acepta valores decimales, enteros, negativos o positivos. Ejemplo: -12.34 o -123.45.', max_digits=5, null=True, verbose_name='Inclinación'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='largo_programado',
            field=models.DecimalField(decimal_places=2, help_text='Este campo acepta valores decimales. Ejemplo. 12345.67', max_digits=10, null=True, verbose_name='Largo Programado'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='largo_real',
            field=models.DecimalField(decimal_places=2, help_text='Este campo predeterminadamente ingresará el valor 0.', max_digits=10, null=True, verbose_name='Largo Real'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='norte',
            field=models.DecimalField(decimal_places=3, help_text='Este campo acepta valores enteros y decimales. Ejemplo, 12345.678.', max_digits=12, null=True, verbose_name='Norte'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='pozo',
            field=models.CharField(help_text='Nombre del pozo asociado a esta recomendación.', max_length=50, null=True, verbose_name='Pozo'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='recomendacion',
            field=models.CharField(help_text='Nombre de la recomendación.', max_length=50, null=True, verbose_name='Recomendación'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='sector',
            field=models.CharField(help_text='Nombre del sector asociado a esta recomendación.', max_length=50, null=True, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='sonda',
            field=models.ForeignKey(help_text='En caso de elegir una sonda diferente, debe crearla previamente en el módulo de gestión de sondas.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='core.sondas', verbose_name='Sonda'),
        ),
    ]
