# Generated by Django 5.1.1 on 2025-01-29 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_recomendacion_azimut_alter_recomendacion_cota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacion',
            name='azimut',
            field=models.IntegerField(help_text='Este campo acepta únicamente valores enteros entre 0 y 360.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Azimut'),
        ),
    ]
