# Generated by Django 5.1.1 on 2025-02-04 15:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_recomendacion_azimut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacion',
            name='azimut',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Azimut'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='cota',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Cota'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='este',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='Este'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='fecha_inicio',
            field=models.DateTimeField(null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='inclinacion',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Inclinación'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='largo_programado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Largo Programado'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='largo_real',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Largo Real'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='norte',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='Norte'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='pozo',
            field=models.CharField(max_length=50, null=True, verbose_name='Pozo'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='recomendacion',
            field=models.CharField(max_length=50, null=True, verbose_name='Recomendación'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='sector',
            field=models.CharField(max_length=50, null=True, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='sonda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='core.sondas', verbose_name='Sonda'),
        ),
    ]
