# Generated by Django 5.1.1 on 2025-03-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_recomendacion_azimut_alter_recomendacion_cota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocultaropcionesvehiculo',
            name='dispositivosomnolencia',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Dispositivos de Somnolencia'),
        ),
        migrations.AddField(
            model_name='ocultaropcionesvehiculo',
            name='tarjetadecombustible',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Tarjeta de Combustible'),
        ),
    ]
