# Generated by Django 5.1.1 on 2025-03-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_ocultaropcionesvehiculo_dispositivosomnolencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocultaropcionesvehiculo',
            old_name='tarjetadecombustible',
            new_name='tarjetaCombustible',
        ),
    ]
