# Generated by Django 5.1.1 on 2025-03-27 19:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_rename_tarjetadecombustible_ocultaropcionesvehiculo_tarjetacombustible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campana', models.CharField(max_length=100, null=True, verbose_name='Campaña')),
                ('metros', models.IntegerField(null=True, verbose_name='Metros Planificados (Mts)')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'db_table': 'drilling_campaing',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(max_length=100, null=True, verbose_name='Programa')),
                ('metros', models.IntegerField(null=True, verbose_name='Metros Planificados (Mts)')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('campana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.campana', verbose_name='Campaña')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'db_table': 'drilling_program',
            },
        ),
    ]
