# Generated by Django 5.1.1 on 2025-03-28 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_campana_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='campana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.campana', verbose_name='Campaña'),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='programa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.programa', verbose_name='Programa'),
        ),
    ]
