# Generated by Django 5.1.1 on 2025-04-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_recomendacion_campana_recomendacion_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='anoFinal',
            field=models.IntegerField(null=True, verbose_name='Año Final'),
        ),
        migrations.AddField(
            model_name='campana',
            name='anoInicial',
            field=models.IntegerField(null=True, verbose_name='Año Inicial'),
        ),
    ]
