# Generated by Django 4.2.11 on 2025-04-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_campana_anofinal_campana_anoinicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='estado',
            field=models.CharField(choices=[('1', 'Abortado'), ('2', 'En Avance'), ('3', 'En Espera'), ('4', 'Finalizado')], max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='manteo',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Manteo'),
        ),
    ]
