# Generated by Django 4.2.11 on 2025-04-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_recomendacion_estado_recomendacion_manteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacion',
            name='manteo',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Manteo'),
        ),
    ]
