# Generated by Django 4.2.11 on 2025-04-26 04:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_recomendacion_manteo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacionFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('este', models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='Este')),
                ('norte', models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='Norte')),
                ('cota', models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Cota')),
                ('fecha', models.DateTimeField(null=True, verbose_name='Fecha')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('recomendacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.recomendacion', verbose_name='Recomendación')),
            ],
            options={
                'verbose_name': 'Recomendacion Final',
                'verbose_name_plural': 'Recomendaciones Finales',
                'db_table': 'drilling_recommendation_final',
            },
        ),
        migrations.CreateModel(
            name='RecomendacionAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azimut', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Azimut')),
                ('este', models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='Este')),
                ('norte', models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='Norte')),
                ('cota', models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Cota')),
                ('manteo', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Manteo')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('recomendacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.recomendacion', verbose_name='Recomendación')),
            ],
            options={
                'verbose_name': 'Recomendacion Ajuste',
                'verbose_name_plural': 'Recomendaciones Ajustes',
                'db_table': 'drilling_recommendation_ajuste',
            },
        ),
    ]
