# Generated by Django 4.2.11 on 2025-04-26 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_recomendacionfinal_recomendacionajuste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomendacionajuste',
            old_name='azimut',
            new_name='azimutAjuste',
        ),
        migrations.RenameField(
            model_name='recomendacionajuste',
            old_name='cota',
            new_name='cotaAjuste',
        ),
        migrations.RenameField(
            model_name='recomendacionajuste',
            old_name='este',
            new_name='esteAjuste',
        ),
        migrations.RenameField(
            model_name='recomendacionajuste',
            old_name='fechacreacion',
            new_name='fechacreacionAjuste',
        ),
        migrations.RenameField(
            model_name='recomendacionajuste',
            old_name='manteo',
            new_name='manteoAjuste',
        ),
        migrations.RenameField(
            model_name='recomendacionajuste',
            old_name='norte',
            new_name='norteAjuste',
        ),
        migrations.RenameField(
            model_name='recomendacionajuste',
            old_name='recomendacion',
            new_name='recomendacionAjuste',
        ),
        migrations.RenameField(
            model_name='recomendacionajuste',
            old_name='status',
            new_name='statusAjuste',
        ),
        migrations.RenameField(
            model_name='recomendacionfinal',
            old_name='cota',
            new_name='cotaFinal',
        ),
        migrations.RenameField(
            model_name='recomendacionfinal',
            old_name='este',
            new_name='esteFinal',
        ),
        migrations.RenameField(
            model_name='recomendacionfinal',
            old_name='fecha',
            new_name='fechaFinal',
        ),
        migrations.RenameField(
            model_name='recomendacionfinal',
            old_name='fechacreacion',
            new_name='fechacreacionFinal',
        ),
        migrations.RenameField(
            model_name='recomendacionfinal',
            old_name='norte',
            new_name='norteFinal',
        ),
        migrations.RenameField(
            model_name='recomendacionfinal',
            old_name='recomendacion',
            new_name='recomendacionFinal',
        ),
        migrations.RenameField(
            model_name='recomendacionfinal',
            old_name='status',
            new_name='statusFinal',
        ),
    ]
