# Generated by Django 4.2.11 on 2025-05-11 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_rename_azimut_recomendacionajuste_azimutajuste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='faena',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faena', verbose_name='Faena'),
        ),
    ]
