# Generated by Django 4.2.11 on 2025-07-16 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_campana_faena'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='fechaUpdateEstado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
