# Generated by Django 4.2.16 on 2026-02-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_recomendacion_fechaupdateestado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programa',
            unique_together={('campana', 'programa')},
        ),
    ]
