# Generated by Django 5.1.1 on 2025-03-19 02:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0049_rename_tarjetadecombustible_ocultaropcionesvehiculo_tarjetacombustible'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca - Modelo')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Marca o Modelo',
                'verbose_name_plural': 'Marca o Modelos',
                'db_table': 'equipment_brand-model',
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, unique=True, verbose_name='Tipo Equipo')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'db_table': 'equipment_type',
            },
        ),
        migrations.CreateModel(
            name='NuevoEquipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50, verbose_name='Ubicación')),
                ('ultimaMantencion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha última mantención')),
                ('frecuencia', models.IntegerField(null=True, verbose_name='Frecuencia Mantención (Meses)')),
                ('proximaMantencion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha última mantención')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('faena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faena')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.marcaequipo')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.tipoequipo')),
            ],
            options={
                'verbose_name': 'Nuevo Equipo',
                'verbose_name_plural': 'Nuevos Equipos',
                'db_table': 'equipment_new_equipment',
            },
        ),
        migrations.AddField(
            model_name='marcaequipo',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.tipoequipo'),
        ),
    ]
