# Generated by Django 5.1.1 on 2025-03-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevoequipamiento',
            name='notasAdicionales',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Notas Adicionales'),
        ),
        migrations.AlterField(
            model_name='nuevoequipamiento',
            name='area',
            field=models.CharField(max_length=50, verbose_name='Área / Ubicación'),
        ),
        migrations.AlterField(
            model_name='nuevoequipamiento',
            name='proximaMantencion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha próxima mantención'),
        ),
    ]
