# Generated by Django 5.1.1 on 2024-11-13 03:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0037_alter_materialescaseta_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistMaterialesSonda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(null=True, verbose_name='Cantidad')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materialessonda', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Checklist Material Sonda',
                'verbose_name_plural': 'Checklist Materiales Sonda',
                'db_table': 'checklist_documentos_materiales_sonda',
            },
        ),
    ]
