# Generated by Django 5.1.1 on 2024-11-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistmaterialessonda',
            name='fecha_checklist',
            field=models.DateTimeField(null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='checklistmaterialessonda',
            name='id_checklist',
            field=models.IntegerField(null=True, verbose_name='ID Checklist'),
        ),
        migrations.AddField(
            model_name='checklistmaterialessonda',
            name='jornada',
            field=models.CharField(choices=[('1', 'Inicio Jornada'), ('2', 'Final Jornada')], max_length=50, null=True, verbose_name='Jornada'),
        ),
        migrations.AddField(
            model_name='checklistmaterialessonda',
            name='turno',
            field=models.CharField(choices=[('1', 'Turno A'), ('2', 'Turno B')], max_length=50, null=True, verbose_name='Turno'),
        ),
    ]
