# Generated by Django 5.1.1 on 2024-11-13 08:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_checklistmaterialessonda_fecha_checklist_and_more'),
        ('core', '0037_alter_materialescaseta_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistMaterialesCaseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.IntegerField(null=True, verbose_name='B')),
                ('m', models.IntegerField(null=True, verbose_name='M')),
                ('observacion', models.CharField(max_length=500, null=True, verbose_name='Observaciones')),
                ('fecha_control', models.DateTimeField(null=True, verbose_name='Fecha Control')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('creador_cargo', models.CharField(max_length=50, null=True, verbose_name='Cargo')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('jornada', models.CharField(choices=[('1', 'Inicio Jornada'), ('2', 'Final Jornada')], max_length=50, null=True, verbose_name='Jornada')),
                ('turno', models.CharField(choices=[('1', 'Turno A'), ('2', 'Turno B')], max_length=50, null=True, verbose_name='Turno')),
                ('id_checklist', models.IntegerField(null=True, verbose_name='ID Checklist')),
                ('fecha_checklist', models.DateTimeField(null=True, verbose_name='Fecha Checklist')),
                ('fecha_revision', models.DateTimeField(null=True, verbose_name='Fecha Revision')),
                ('observaciones_revision', models.CharField(max_length=500, null=True, verbose_name='Observaciones Revision')),
                ('supervisor', models.CharField(max_length=50, null=True, verbose_name='Supervisor')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materialessonda', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Checklist Material Caseta',
                'verbose_name_plural': 'Checklist Materiales Caseta',
                'db_table': 'checklist_documentos_materiales_caseta',
            },
        ),
    ]
