# Generated by Django 5.1.1 on 2024-11-13 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_checklistmaterialescaseta'),
        ('core', '0037_alter_materialescaseta_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistmaterialescaseta',
            name='jornada',
        ),
        migrations.AlterField(
            model_name='checklistmaterialescaseta',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materialescaseta', verbose_name='Item'),
        ),
    ]
