# Generated by Django 5.1.1 on 2024-11-27 04:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_remove_checklistmaterialescaseta_jornada_and_more'),
        ('core', '0037_alter_materialescaseta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistmaterialessonda',
            name='etapa',
            field=models.CharField(max_length=50, null=True, verbose_name='Etapa'),
        ),
        migrations.AddField(
            model_name='checklistmaterialessonda',
            name='sonda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sondas', verbose_name='Sonda'),
        ),
        migrations.AddField(
            model_name='checklistmaterialessonda',
            name='sondajeCodigo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sondajes', verbose_name='Sondaje'),
        ),
        migrations.AddField(
            model_name='checklistmaterialessonda',
            name='sondajeEstado',
            field=models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B')], default='', max_length=3, null=True, verbose_name='Gemelo'),
        ),
        migrations.AddField(
            model_name='checklistmaterialessonda',
            name='sondajeSerie',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(3940), django.core.validators.MaxValueValidator(4400)], verbose_name='Serie'),
        ),
    ]
