# Generated by Django 5.1.1 on 2024-11-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_checklistmaterialessonda_etapa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistmaterialessonda',
            name='progreso',
            field=models.CharField(default='Creado', max_length=50, null=True, verbose_name='Progreso'),
        ),
    ]
