# Generated by Django 5.1.1 on 2024-12-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_checklistmaterialessonda_progreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistmaterialessonda',
            name='id_checklist',
            field=models.BigIntegerField(null=True, verbose_name='ID Checklist'),
        ),
    ]
