# Generated by Django 5.1.1 on 2024-12-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_alter_checklistmaterialessonda_id_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistmaterialessonda',
            name='cantidad',
            field=models.IntegerField(default=0, null=True, verbose_name='Cantidad'),
        ),
    ]
