# Generated by Django 5.1.1 on 2025-01-14 02:18

import checklist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0008_alter_checklistmaterialessonda_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistmaterialescaseta',
            name='fotografiaMaterial',
            field=models.ImageField(blank=True, default='checklist_caseta/no-imagen.png', null=True, upload_to=checklist.models.ChecklistMaterialesCaseta.generaNombre, verbose_name='Fotografía del Material'),
        ),
    ]
