# Generated by Django 4.2.11 on 2025-07-09 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0009_checklistmaterialescaseta_fotografiamaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEtapasReporteDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklistEntrada', models.BooleanField(default=False, null=True, verbose_name='CheckList Entrada')),
                ('reporteDigital', models.BooleanField(default=False, null=True, verbose_name='Reporte Digital')),
                ('checklistSalida', models.BooleanField(default=False, null=True, verbose_name='CheckList Salida')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.checklistmaterialessonda', verbose_name='Reporte')),
            ],
            options={
                'verbose_name': 'Estado de Etapas',
                'verbose_name_plural': 'Estados de Etapas',
                'db_table': 'drilling_reporte_digital_etapas',
            },
        ),
    ]
