# Generated by Django 4.2.11 on 2025-07-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0010_estadoetapasreportedigital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadoetapasreportedigital',
            name='reporte',
        ),
        migrations.AddField(
            model_name='estadoetapasreportedigital',
            name='id_checklist',
            field=models.BigIntegerField(null=True, verbose_name='ID Checklist'),
        ),
    ]
