# Generated by Django 4.2.11 on 2025-07-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0011_remove_estadoetapasreportedigital_reporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoetapasreportedigital',
            name='checklistEntrada',
            field=models.BooleanField(default=True, null=True, verbose_name='CheckList Entrada'),
        ),
        migrations.AlterField(
            model_name='estadoetapasreportedigital',
            name='checklistSalida',
            field=models.BooleanField(default=True, null=True, verbose_name='CheckList Salida'),
        ),
        migrations.AlterField(
            model_name='estadoetapasreportedigital',
            name='reporteDigital',
            field=models.BooleanField(default=True, null=True, verbose_name='Reporte Digital'),
        ),
    ]
