from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect
from django.urls import path, include
from django.contrib.auth.decorators import user_passes_test
from functools import wraps
from .views import dashboard, dashboardSondaje, dashboardPrevencion,dashboardInventario, select, selectOption 
from .views import ( manage_genders, manage_cities, manage_nationalities, manage_years, manage_brands, manage_models, manage_colours, 
                    manage_types, manage_mining, manage_mining_documents, manage_maintenance_companies, manage_maintenance_services, 
                    manage_failures, manage_categories_failures, manage_mining_documents_general, manage_types_machines, manage_brands_machines, 
                    manage_kits_repairs, manage_failures_machines, cargar_kits_por_marca, manage_important_dates, manage_report_error, 
                    manage_help_manuals, manage_campanas, manage_programas)
from .views import (new_gender, new_city, new_nationality, new_year, new_brand, new_model, new_colour, new_campana, new_programa,
                    new_type, new_mining, new_mining_document, new_maintenance_companie, new_maintenance_service, new_failure, new_categories_failure, 
                    new_mining_document_general, new_type_machine, new_brand_machine, new_kit_repair, new_failure_machine, new_important_dates, 
                    new_report_error, new_help_manuals,)
from .views import (save_new_gender, save_new_city, save_new_nationality, save_new_year, save_new_brand, save_new_campana, save_new_programa,
                    save_new_model, save_new_colour, save_new_type, save_new_mining, save_new_mining_document, save_new_maintenance_companie, 
                    save_new_maintenance_service, save_new_failure, save_new_categories_failure, save_new_mining_document_general, 
                    save_new_type_machine, save_new_brand_machine, save_new_kit_repair, save_new_failure_machine, save_new_important_dates, 
                    save_new_report_error, save_new_help_manuals)
from .views import (status_gender, status_city, status_nationality, status_year, status_brand, status_model, status_colour, status_type, status_mining, 
                    status_mining_document, status_maintenance_companie, status_maintenance_service, status_failure, status_categories_failure, 
                    status_mining_document_general, status_type_machine, status_brand_machine, status_kit_repair, status_failure_machine, 
                    status_important_dates, status_help_manuals, status_campana, status_programa)
from .views import (edit_mining, edit_maintenance_companie, edit_type, edit_mining_document_general, edit_kit_repair, edit_important_dates,
                    edit_help_manuals, edit_campana, edit_programa)
from .views import (save_edit_mining, save_edit_maintenance_companie, save_edit_type, save_edit_mining_document_general, save_edit_kit_repair, 
                    save_edit_important_dates, mostrar_reporte_error, save_edit_help_manuals, view_help_manuals, save_edit_campana, save_edit_programa)
from .views import (manage_probe, new_probe, save_new_probe, status_probe, edit_probe, save_edit_probe, 
                    manage_aditivos, new_aditivos, save_new_aditivos, status_aditivos, edit_aditivos, save_edit_aditivos, 
                    manage_cantidadAgua, new_cantidadAgua, save_new_cantidadAgua, status_cantidadAgua, edit_cantidadAgua, save_edit_cantidadAgua, 
                    manage_casing, new_casing, save_new_casing, status_casing, edit_casing, save_edit_casing, cargar_programas_por_campana,
                    manage_corona, new_corona, save_new_corona, status_corona, edit_corona, save_edit_corona, 
                    manage_details, new_details, save_new_details, status_details, edit_details, save_edit_details, 
                    manage_diameter, new_diameter, save_new_diameter, status_diameter, edit_diameter, save_edit_diameter, 
                    manage_drilling, new_drilling, save_new_drilling, status_drilling, edit_drilling, save_edit_drilling,
                    manage_escareador, new_escareador, save_new_escareador, status_escareador, edit_escareador, save_edit_escareador, 
                    manage_largoBarra, new_largoBarra, save_new_largoBarra, status_largoBarra, edit_largoBarra, save_edit_largoBarra,
                    manage_recomendaciones, new_recomendacion, save_new_recomendacion, status_recomendacion, edit_recomendacion, save_edit_recomendacion,
                    manage_orientation, new_orientation, save_new_orientation, status_orientation, edit_orientation, save_edit_orientation,
                    manage_tipoTerreno, new_tipoTerreno, save_new_tipoTerreno, status_tipoTerreno, edit_tipoTerreno, save_edit_tipoTerreno,
                    manage_zapata, new_zapata, save_new_zapata, status_zapata, edit_zapata, save_edit_zapata,
                    manage_perforista, new_perforista, save_new_perforista, status_perforista, edit_perforista, save_edit_perforista,
                    save_edit_recomendacion_ajuste, save_edit_recomendacion_final, update_estado_recomendacion)
from .views import (manage_materiales_sonda, new_materiales_sonda, save_new_materiales_sonda, status_materiales_sonda, edit_materiales_sonda, 
                    save_edit_materiales_sonda, manage_materiales_caseta, new_materiales_caseta, save_new_materiales_caseta, status_materiales_caseta,
                    edit_materiales_caseta, save_edit_materiales_caseta)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('select',select, name="select"),
    path('selectOption',selectOption, name="selectOption"),
    path('dashboard',dashboard, name="dashboard"),
    path('dashboardSondaje',dashboardSondaje, name="dashboardSondaje"),
    path('dashboardPrevencion',dashboardPrevencion, name="dashboardPrevencion"),
    path('manage_genders',manage_genders, name="manage_genders"),
    path('new_gender',new_gender, name="new_gender"),
    path('save_new_gender',save_new_gender, name="save_new_gender"),    
    path('status_gender',status_gender, name="status_gender"),
    path('manage_cities',manage_cities, name="manage_cities"),
    path('new_city',new_city, name="new_city"),
    path('save_new_cities',save_new_city, name="save_new_city"),   
    path('status_city',status_city, name="status_city"), 
    path('manage_nationalities',manage_nationalities, name="manage_nationalities"),    
    path('new_nationality',new_nationality, name="new_nationality"),
    path('save_new_nationality',save_new_nationality, name="save_new_nationality"),  
    path('status_nationality',status_nationality, name="status_nationality"), 
    path('manage_years',manage_years, name="manage_years"),
    path('new_year',new_year, name="new_year"),
    path('save_new_yearr',save_new_year, name="save_new_year"), 
    path('status_year',status_year, name="status_year"), 
    path('manage_brands',manage_brands, name="manage_brands"),
    path('new_brand',new_brand, name="new_brand"),
    path('save_new_brand',save_new_brand, name="save_new_brand"),  
    path('status_brand',status_brand, name="status_brand"),   
    path('manage_models',manage_models, name="manage_models"),
    path('new_model',new_model, name="new_model"),
    path('save_new_model',save_new_model, name="save_new_model"),  
    path('status_model',status_model, name="status_model"),   
    path('manage_colours',manage_colours, name="manage_colours"),
    path('new_colour',new_colour, name="new_colour"),
    path('save_new_colour',save_new_colour, name="save_new_colour"),   
    path('status_colour',status_colour, name="status_colour"),     
    path('manage_types',manage_types, name="manage_types"),
    path('new_type',new_type, name="new_type"),
    path('save_new_type',save_new_type, name="save_new_type"),   
    path('status_type',status_type, name="status_type"),
    path('edit_type',edit_type, name="edit_type"),
    path('save_edit_type',save_edit_type, name="save_edit_type"),
    path('manage_mining',manage_mining, name="manage_mining"),
    path('new_mining',new_mining, name="new_mining"),
    path('save_new_mining',save_new_mining, name="save_new_mining"),   
    path('status_mining',status_mining, name="status_mining"), 
    path('edit_mining',edit_mining, name="edit_mining"), 
    path('save_edit_mining',save_edit_mining, name="save_edit_mining"), 
    path('manage_mining_documents',manage_mining_documents, name="manage_mining_documents"),
    path('new_mining_document',new_mining_document, name="new_mining_document"),
    path('save_new_mining_document',save_new_mining_document, name="save_new_mining_document"),   
    path('status_mining_document',status_mining_document, name="status_mining_document"),
    path('manage_maintenance_companies',manage_maintenance_companies, name="manage_maintenance_companies"),
    path('new_maintenance_companie',new_maintenance_companie, name="new_maintenance_companie"),
    path('save_new_maintenance_companie',save_new_maintenance_companie, name="save_new_maintenance_companie"),   
    path('status_maintenance_companie',status_maintenance_companie, name="status_maintenance_companie"), 
    path('edit_maintenance_companie',edit_maintenance_companie, name="edit_maintenance_companie"),
    path('save_edit_maintenance_companie',save_edit_maintenance_companie, name="save_edit_maintenance_companie"),
    path('manage_maintenance_services',manage_maintenance_services, name="manage_maintenance_services"),
    path('new_maintenance_service',new_maintenance_service, name="new_maintenance_service"),
    path('save_new_maintenance_service',save_new_maintenance_service, name="save_new_maintenance_service"),   
    path('status_maintenance_service',status_maintenance_service, name="status_maintenance_service"),
    path('manage_failures',manage_failures, name="manage_failures"),
    path('new_failure',new_failure, name="new_failure"),
    path('save_new_failure',save_new_failure, name="save_new_failure"),   
    path('status_failure',status_failure, name="status_failure"),
    path('manage_categories_failures',manage_categories_failures, name="manage_categories_failures"),
    path('new_categories_failure',new_categories_failure, name="new_categories_failure"),
    path('save_new_categories_failure',save_new_categories_failure, name="save_new_categories_failure"),   
    path('status_categories_failure',status_categories_failure, name="status_categories_failure"),
    path('manage_mining_documents_general',manage_mining_documents_general, name="manage_mining_documents_general"),
    path('new_mining_document_general',new_mining_document_general, name="new_mining_document_general"),
    path('save_new_mining_document_general',save_new_mining_document_general, name="save_new_mining_document_general"),   
    path('status_mining_document_general',status_mining_document_general, name="status_mining_document_general"),
    path('edit_mining_document_general',edit_mining_document_general, name="edit_mining_document_general"),
    path('save_edit_mining_document_general',save_edit_mining_document_general, name="save_edit_mining_document_general"),
    path('manage_types_machines',manage_types_machines, name="manage_types_machines"),
    path('new_type_machine',new_type_machine, name="new_type_machine"),
    path('save_new_type_machine',save_new_type_machine, name="save_new_type_machine"),
    path('status_type_machine',status_type_machine, name="status_type_machine"),
    path('manage_brands_machines',manage_brands_machines, name="manage_brands_machines"),
    path('new_brand_machine',new_brand_machine, name="new_brand_machine"),
    path('save_new_brand_machine',save_new_brand_machine, name="save_new_brand_machine"),   
    path('status_brand_machine',status_brand_machine, name="status_brand_machine"),
    path('manage_kits_repairs',manage_kits_repairs, name="manage_kits_repairs"),
    path('new_kit_repair',new_kit_repair, name="new_kit_repair"),
    path('save_new_kit_repair',save_new_kit_repair, name="save_new_kit_repair"),
    path('status_kit_repair',status_kit_repair, name="status_kit_repair"),
    path('edit_kit_repair',edit_kit_repair, name="edit_kit_repair"),
    path('save_edit_kit_repair',save_edit_kit_repair, name="save_edit_kit_repair"),
    path('manage_failures_machines',manage_failures_machines, name="manage_failures_machines"),
    path('new_failure_machine',new_failure_machine, name="new_failure_machine"),
    path('save_new_failure_machine',save_new_failure_machine, name="save_new_failure_machine"),   
    path('status_failure_machine',status_failure_machine, name="status_failure_machine"),
    path('cargar_kits_por_marca',cargar_kits_por_marca, name="cargar_kits_por_marca"),
    path('new_important_dates',new_important_dates, name="new_important_dates"),
    path('save_new_important_dates',save_new_important_dates, name="save_new_important_dates"),
    path('manage_important_dates',manage_important_dates, name="manage_important_dates"),
    path('status_important_dates',status_important_dates, name="status_important_dates"),
    path('edit_important_dates',edit_important_dates, name="edit_important_dates"),
    path('save_edit_important_dates',save_edit_important_dates, name="save_edit_important_dates"),
    path('manage_report_error',manage_report_error, name="manage_report_error"),
    path('new_report_error',new_report_error, name="new_report_error"),
    path('save_new_report_error',save_new_report_error, name="save_new_report_error"),
    path('mostrar_reporte_error/<int:id>',mostrar_reporte_error, name="mostrar_reporte_error"),
    path('manage_help_manuals',manage_help_manuals, name="manage_help_manuals"),
    path('new_help_manuals',new_help_manuals, name="new_help_manuals"),
    path('save_new_help_manuals',save_new_help_manuals, name="save_new_help_manuals"),
    path('edit_help_manuals',edit_help_manuals, name="edit_help_manuals"),
    path('save_edit_help_manuals',save_edit_help_manuals, name="save_edit_help_manuals"),
    path('status_help_manuals',status_help_manuals, name="status_help_manuals"),
    path('view_help_manuals',view_help_manuals, name="view_help_manuals"),
    path('manage_probe',manage_probe, name="manage_probe"),
    path('new_probe',new_probe, name="new_probe"),
    path('save_new_probe',save_new_probe, name="save_new_probe"),
    path('status_probe',status_probe, name="status_probe"),
    path('edit_probe',edit_probe, name="edit_probe"),
    path('save_edit_probe',save_edit_probe, name="save_edit_probe"),
    path('manage_aditivos',manage_aditivos, name="manage_aditivos"),
    path('new_aditivos',new_aditivos, name="new_aditivos"),
    path('save_new_aditivos',save_new_aditivos, name="save_new_aditivos"),
    path('status_aditivos',status_aditivos, name="status_aditivos"),
    path('edit_aditivos',edit_aditivos, name="edit_aditivos"),
    path('save_edit_aditivos',save_edit_aditivos, name="save_edit_aditivos"),
    path('manage_cantidadAgua',manage_cantidadAgua, name="manage_cantidadAgua"),
    path('new_cantidadAgua',new_cantidadAgua, name="new_cantidadAgua"),
    path('save_new_cantidadAgua',save_new_cantidadAgua, name="save_new_cantidadAgua"),
    path('status_cantidadAgua',status_cantidadAgua, name="status_cantidadAgua"),
    path('edit_cantidadAgua',edit_cantidadAgua, name="edit_cantidadAgua"),
    path('save_edit_cantidadAgua',save_edit_cantidadAgua, name="save_edit_cantidadAgua"),
    path('manage_casing',manage_casing, name="manage_casing"),
    path('new_casing',new_casing, name="new_casing"),
    path('save_new_casing',save_new_casing, name="save_new_casing"),
    path('status_casing',status_casing, name="status_casing"),
    path('edit_casing',edit_casing, name="edit_casing"),
    path('save_edit_casing',save_edit_casing, name="save_edit_casing"),
    path('manage_corona',manage_corona, name="manage_corona"),
    path('new_corona',new_corona, name="new_corona"),
    path('save_new_corona',save_new_corona, name="save_new_corona"),
    path('status_corona',status_corona, name="status_corona"),
    path('edit_corona',edit_corona, name="edit_corona"),
    path('save_edit_corona',save_edit_corona, name="save_edit_corona"),
    path('manage_details',manage_details, name="manage_details"),
    path('new_details',new_details, name="new_details"),
    path('save_new_details',save_new_details, name="save_new_details"),
    path('status_details',status_details, name="status_details"),
    path('edit_details',edit_details, name="edit_details"),
    path('save_edit_details',save_edit_details, name="save_edit_details"),
    path('manage_diameter',manage_diameter, name="manage_diameter"), 
    path('new_diameter',new_diameter, name="new_diameter"),
    path('save_new_diameter',save_new_diameter, name="save_new_diameter"),
    path('status_diameter',status_diameter, name="status_diameter"),
    path('edit_diameter',edit_diameter, name="edit_diameter"),
    path('save_edit_diameter',save_edit_diameter, name="save_edit_diameter"),
    path('manage_drilling',manage_drilling, name="manage_drilling"),
    path('new_drilling',new_drilling, name="new_drilling"),
    path('save_new_drilling',save_new_drilling, name="save_new_drilling"),
    path('status_drilling',status_drilling, name="status_drilling"),
    path('edit_drilling',edit_drilling, name="edit_drilling"),
    path('save_edit_drilling',save_edit_drilling, name="save_edit_drilling"),
    path('manage_escareador',manage_escareador, name="manage_escareador"),
    path('new_escareador',new_escareador, name="new_escareador"),
    path('save_new_escareador',save_new_escareador, name="save_new_escareador"),
    path('status_escareador',status_escareador, name="status_escareador"),
    path('edit_escareador',edit_escareador, name="edit_escareador"),
    path('save_edit_escareador',save_edit_escareador, name="save_edit_escareador"),
    path('manage_largoBarra',manage_largoBarra, name="manage_largoBarra"),
    path('new_largoBarra',new_largoBarra, name="new_largoBarra"),
    path('save_new_largoBarra',save_new_largoBarra, name="save_new_largoBarra"),
    path('status_largoBarra',status_largoBarra, name="status_largoBarra"),
    path('edit_largoBarra',edit_largoBarra, name="edit_largoBarra"),
    path('save_edit_largoBarra',save_edit_largoBarra, name="save_edit_largoBarra"),
    ########################
    path('manage_recomendacion',manage_recomendaciones, name="manage_recomendacion"),
    path('new_recomendacion',new_recomendacion, name="new_recomendacion"),
    path('save_new_recomendacion',save_new_recomendacion, name="save_new_recomendacion"),
    path('status_recomendacion',status_recomendacion, name="status_recomendacion"),
    path('edit_recomendacion',edit_recomendacion, name="edit_recomendacion"),
    path('save_edit_recomendacion',save_edit_recomendacion, name="save_edit_recomendacion"),
    path('save_edit_recomendacion_ajuste',save_edit_recomendacion_ajuste, name="save_edit_recomendacion_ajuste"),
    path('save_edit_recomendacion_final',save_edit_recomendacion_final, name="save_edit_recomendacion_final"),
    path('update_estado_recomendacion', update_estado_recomendacion, name='update_estado_recomendacion'),

    path('cargar_programas_por_campana',cargar_programas_por_campana, name="cargar_programas_por_campana"),
    path('manage_campanas',manage_campanas, name="manage_campanas"),
    path('new_campana',new_campana, name="new_campana"),
    path('save_new_campana',save_new_campana, name="save_new_campana"),
    path('status_campana',status_campana, name="status_campana"),
    path('edit_campana',edit_campana, name="edit_campana"),
    path('save_edit_campana',save_edit_campana, name="save_edit_campana"),
    path('manage_programas',manage_programas, name="manage_programas"),
    path('new_programa',new_programa, name="new_programa"),
    path('save_new_programa',save_new_programa, name="save_new_programa"),
    path('status_programa',status_programa, name="status_programa"),
    path('edit_programa',edit_programa, name="edit_programa"),
    path('save_edit_programa',save_edit_programa, name="save_edit_programa"),
    ########################
    path('manage_orientation',manage_orientation, name="manage_orientation"),
    path('new_orientation',new_orientation, name="new_orientation"),
    path('save_new_orientation',save_new_orientation, name="save_new_orientation"),
    path('status_orientation',status_orientation, name="status_orientation"),
    path('edit_orientation',edit_orientation, name="edit_orientation"),
    path('save_edit_orientation',save_edit_orientation, name="save_edit_orientation"),
    path('manage_tipoTerreno',manage_tipoTerreno, name="manage_tipoTerreno"),
    path('new_tipoTerreno',new_tipoTerreno, name="new_tipoTerreno"),
    path('save_new_tipoTerreno',save_new_tipoTerreno, name="save_new_tipoTerreno"),
    path('status_tipoTerreno',status_tipoTerreno, name="status_tipoTerreno"),
    path('edit_tipoTerreno',edit_tipoTerreno, name="edit_tipoTerreno"),
    path('save_edit_tipoTerreno',save_edit_tipoTerreno, name="save_edit_tipoTerreno"),
    path('manage_zapata',manage_zapata, name="manage_zapata"),
    path('new_zapata',new_zapata, name="new_zapata"),
    path('save_new_zapata',save_new_zapata, name="save_new_zapata"),
    path('status_zapata',status_zapata, name="status_zapata"),
    path('edit_zapata',edit_zapata, name="edit_zapata"),
    path('save_edit_zapata',save_edit_zapata, name="save_edit_zapata"),
    path('manage_perforista',manage_perforista, name="manage_perforista"),
    path('new_perforista',new_perforista, name="new_perforista"),
    path('save_new_perforista',save_new_perforista, name="save_new_perforista"),
    path('status_perforista',status_perforista, name="status_perforista"),
    path('edit_perforista',edit_perforista, name="edit_perforista"),
    path('save_edit_perforista',save_edit_perforista, name="save_edit_perforista"),
    path('manage_materiales_sonda',manage_materiales_sonda, name="manage_materiales_sonda"),
    path('new_materiales_sonda',new_materiales_sonda, name="new_materiales_sonda"),
    path('save_new_materiales_sonda',save_new_materiales_sonda, name="save_new_materiales_sonda"),
    path('status_materiales_sonda',status_materiales_sonda, name="status_materiales_sonda"),
    path('edit_materiales_sonda',edit_materiales_sonda, name="edit_materiales_sonda"),
    path('save_edit_materiales_sonda',save_edit_materiales_sonda, name="save_edit_materiales_sonda"),
    path('manage_materiales_caseta',manage_materiales_caseta, name="manage_materiales_caseta"),
    path('new_materiales_caseta',new_materiales_caseta, name="new_materiales_caseta"),
    path('save_new_materiales_caseta',save_new_materiales_caseta, name="save_new_materiales_caseta"),
    path('status_materiales_caseta',status_materiales_caseta, name="status_materiales_caseta"),
    path('edit_materiales_caseta',edit_materiales_caseta, name="edit_materiales_caseta"),
    path('save_edit_materiales_caseta',save_edit_materiales_caseta, name="save_edit_materiales_caseta"),
    ######################INVENTARIO##################
    path('dashboardInventario',dashboardInventario, name="dashboardInventario"),
]