# Generated by Django 5.0.1 on 2024-06-16 10:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0029_alter_fechasimportantes_fechavencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionFaenas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(blank=True, choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=15, null=True, verbose_name='Meses')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Valor')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('faena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faena')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo')),
            ],
            options={
                'verbose_name': 'Planificación por Faena y Tipo de Vehículo',
                'verbose_name_plural': 'Planificación por Faena y Tipo de Vehículos',
                'db_table': 'planning_minning_type',
            },
        ),
    ]
