# Generated by Django 5.1.1 on 2025-04-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_planificacioncampanas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificacioncampanas',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='planificacioncampanas',
            name='acumuladoPlan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Acumulado Plan'),
        ),
        migrations.AddField(
            model_name='planificacioncampanas',
            name='acumuladoReal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Acumulado Real'),
        ),
        migrations.AddField(
            model_name='planificacioncampanas',
            name='plan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='planificacioncampanas',
            name='realMensual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Real Mensual'),
        ),
    ]
