# Generated by Django 5.1.1 on 2025-04-10 02:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_campana_anofinal_campana_anoinicial'),
        ('planning', '0003_remove_planificacioncampanas_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(blank=True, choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=15, null=True, verbose_name='Meses')),
                ('plan', models.IntegerField(blank=True, null=True, verbose_name='Plan')),
                ('realMensual', models.IntegerField(blank=True, null=True, verbose_name='Real Mensual')),
                ('acumuladoPlan', models.IntegerField(blank=True, null=True, verbose_name='Acumulado Plan')),
                ('acumuladoReal', models.IntegerField(blank=True, null=True, verbose_name='Acumulado Real')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campana', verbose_name='Campañas')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programa', verbose_name='Programas')),
            ],
            options={
                'verbose_name': 'Planificación de Programa',
                'verbose_name_plural': 'Planificación de Programas',
                'db_table': 'planning_drilling_program',
            },
        ),
    ]
