# Generated by Django 5.1.1 on 2025-04-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_planificacionprograma'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacionprograma',
            name='ano',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
    ]
