# Generated by Django 5.1.1 on 2025-04-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_planificacionprograma_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacionprograma',
            name='acumuladoPlan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Acumulado Plan'),
        ),
        migrations.AlterField(
            model_name='planificacionprograma',
            name='acumuladoReal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Acumulado Real'),
        ),
        migrations.AlterField(
            model_name='planificacionprograma',
            name='plan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='planificacionprograma',
            name='realMensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Real Mensual'),
        ),
    ]
