# Generated by Django 5.0.1 on 2024-02-24 00:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placaPatente', models.CharField(max_length=25, unique=True, verbose_name='Placa Patente')),
                ('fechaAdquisicion', models.DateTimeField(null=True, verbose_name='Fecha Adquisición')),
                ('nombrePropietario', models.CharField(max_length=50, verbose_name='Nombre Propietario')),
                ('rutPropietario', models.CharField(max_length=50, verbose_name='Rut Propietario')),
                ('domicilio', models.CharField(max_length=15, verbose_name='Domicilio')),
                ('numeroMotor', models.CharField(max_length=25, unique=True, verbose_name='N° Motor')),
                ('numeroChasis', models.CharField(max_length=25, unique=True, verbose_name='N° Chasis')),
                ('numeroVin', models.CharField(max_length=25, unique=True, verbose_name='N° Vin')),
                ('fechaVencimientoPermisoCirculacion', models.DateTimeField(null=True, verbose_name='Fecha Permiso Circulación (Vencimiento)')),
                ('fechaVencimientoRevisionTecnica', models.DateTimeField(null=True, verbose_name='Fecha Revisión Tecnica (Vencimiento)')),
                ('fechaVencimientoSeguroObligatorio', models.DateTimeField(null=True, verbose_name='Fecha Seguro Obligatorio (Vencimiento)')),
                ('fechaInstalacionGps', models.DateTimeField(null=True, verbose_name='Fecha Instalación Gps')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('ano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ano', verbose_name='Año')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.color', verbose_name='Color')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.marca', verbose_name='Marca')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.modelo', verbose_name='Modelo')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'db_table': 'vehicle_profile',
            },
        ),
    ]
