# Generated by Django 5.0.1 on 2024-03-05 05:50

import django.db.models.deletion
import vehicle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentacionesVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografiaPadron', models.ImageField(blank=True, default='documentacion_usuario/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre)),
                ('fotografiaPermisoCirculacion', models.ImageField(blank=True, default='documentacion_usuario/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre)),
                ('fotografiaRevisionTecnica', models.ImageField(blank=True, default='documentacion_usuario/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre)),
                ('fotografiaRevisionTecnicaGases', models.ImageField(blank=True, default='documentacion_usuario/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre)),
                ('fotografiaSeguroObligatorio', models.ImageField(blank=True, default='documentacion_usuario/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre)),
                ('fotografiaCertificadoGps', models.ImageField(blank=True, default='documentacion_usuario/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre)),
                ('fotografiaCertificadoVarios', models.ImageField(blank=True, default='documentacion_usuario/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre)),
                ('fotografiaInteriorTablero', models.ImageField(blank=True, default='documentacion_usuario/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre)),
                ('fotografiaInteriorCopiloto', models.ImageField(blank=True, default='documentacion_usuario/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre)),
                ('fotografiaInteriorAtrasPiloto', models.ImageField(blank=True, default='documentacion_usuario/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre)),
                ('fotografiaInteriorAtrasCopiloto', models.ImageField(blank=True, default='documentacion_usuario/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre)),
                ('fotografiaExteriorFrontis', models.ImageField(blank=True, default='documentacion_usuario/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre)),
                ('fotografiaExteriorAtras', models.ImageField(blank=True, default='documentacion_usuario/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre)),
                ('fotografiaExteriorPiloto', models.ImageField(blank=True, default='documentacion_usuario/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre)),
                ('fotografiaExteriorCopiloto', models.ImageField(blank=True, default='documentacion_usuario/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiculo')),
            ],
            options={
                'verbose_name': 'Documentacion Vehiculo',
                'verbose_name_plural': 'Documentacion Vehiculos',
                'db_table': 'vehicle_documentation',
            },
        ),
    ]
