# Generated by Django 5.0.1 on 2024-03-06 00:19

import vehicle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_documentacionesvehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaCertificadoGps',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaCertificadoVarios',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaExteriorAtras',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaExteriorCopiloto',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaExteriorFrontis',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaExteriorPiloto',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaInteriorAtrasCopiloto',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaInteriorAtrasPiloto',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaInteriorCopiloto',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaInteriorTablero',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaPadron',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaPermisoCirculacion',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaRevisionTecnica',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaRevisionTecnicaGases',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaSeguroObligatorio',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
    ]
