# Generated by Django 5.0.1 on 2024-03-06 20:05

import vehicle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_alter_documentacionesvehiculo_fotografiacertificadogps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaExteriorAtras',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen-vehiculo.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaExteriorCopiloto',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen-vehiculo.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaExteriorFrontis',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen-vehiculo.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaExteriorPiloto',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen-vehiculo.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaInteriorAtrasCopiloto',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen-vehiculo.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaInteriorAtrasPiloto',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen-vehiculo.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaInteriorCopiloto',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen-vehiculo.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaInteriorTablero',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen-vehiculo.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='domicilio',
            field=models.CharField(max_length=100, verbose_name='Domicilio'),
        ),
    ]
