# Generated by Django 5.0.1 on 2024-03-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_documentacionesvehiculo_fotografiaexterioratras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='fechaAdquisicion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Adquisición'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fechaInstalacionGps',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Instalación Gps'),
        ),
    ]
