# Generated by Django 5.0.1 on 2024-03-12 21:16

import django.db.models.deletion
import vehicle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_alter_vehiculo_fechaadquisicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacionesvehiculo',
            name='FotografiaCertificadoBarraAntiVuelco',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AddField(
            model_name='documentacionesvehiculo',
            name='fotografiaCertificadoLamina',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AddField(
            model_name='documentacionesvehiculo',
            name='fotografiaFacturaCompra',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AddField(
            model_name='documentacionesvehiculo',
            name='fotografiaSeguroAutomotriz',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.CreateModel(
            name='InformacionTecnicaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoTraccion', models.CharField(blank=True, choices=[('4x2', '4x2'), ('4x4', '4x4')], max_length=10, null=True, verbose_name='Tracción')),
                ('pesoBrutoVehicular', models.IntegerField(blank=True, null=True, verbose_name='Peso Bruto Vehicular')),
                ('capacidadCarga', models.IntegerField(blank=True, null=True, verbose_name='Capacidad de Carga')),
                ('tipoNeumatico', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Neumatico')),
                ('tipoAceiteMotor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Aceite Motor')),
                ('tipoRefrigeranteMotor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Liquido Refrigerante')),
                ('tipoFiltroAireMotor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Filtro Aire')),
                ('tipoFiltoCombustible', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Filtro Combustible')),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiculo')),
            ],
            options={
                'verbose_name': 'Información Técnica de Vehiculo',
                'verbose_name_plural': 'Información Técnica de Vehiculo',
                'db_table': 'vehicle_information',
            },
        ),
    ]
