# Generated by Django 5.0.1 on 2024-03-12 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_documentacionesvehiculo_fotografiacertificadobarraantivuelco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentacionesvehiculo',
            old_name='FotografiaCertificadoBarraAntiVuelco',
            new_name='fotografiaCertificadoBarraAntiVuelco',
        ),
    ]
