# Generated by Django 5.0.1 on 2024-03-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_rename_fotografiacertificadobarraantivuelco_documentacionesvehiculo_fotografiacertificadobarraantivu'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='fechaInstalacionBarraAntiVuelco',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Instalación Barra AntiVuelco'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fechaVencimientoLamina',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Vencimiento Lamina'),
        ),
    ]
