# Generated by Django 5.0.1 on 2024-03-13 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_vehiculo_fechainstalacionbarraantivuelco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informaciontecnicavehiculo',
            old_name='tipoFiltoCombustible',
            new_name='tipoFiltroCombustible',
        ),
    ]
