# Generated by Django 5.0.1 on 2024-03-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_rename_tipofiltocombustible_informaciontecnicavehiculo_tipofiltrocombustible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informaciontecnicavehiculo',
            name='capacidadCarga',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacidad de Carga (kg)'),
        ),
        migrations.AlterField(
            model_name='informaciontecnicavehiculo',
            name='pesoBrutoVehicular',
            field=models.IntegerField(blank=True, null=True, verbose_name='Peso Bruto Vehicular (kg)'),
        ),
    ]
