# Generated by Django 5.0.1 on 2024-03-27 18:50

import vehicle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_alter_informaciontecnicavehiculo_capacidadcarga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacionesvehiculo',
            name='fotografiaDocumentacionMiniBus',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tieneGps',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=20, null=True, verbose_name='Tiene GPS Instalado?'),
        ),
    ]
