# Generated by Django 5.0.1 on 2024-03-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_documentacionesvehiculo_fotografiadocumentacionminibus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='tieneGps',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tieneTag',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=20, null=True, verbose_name='Tiene Tag Asociado?'),
        ),
    ]
