# Generated by Django 5.0.1 on 2024-03-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_remove_vehiculo_tienegps_vehiculo_tienetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='fechaVencimientoTransportePrivado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Vencimiento Trasnporte Privado Remunerado'),
        ),
    ]
