# Generated by Django 5.0.1 on 2024-03-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0013_vehiculo_fechavencimientotransporteprivado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='fechaInstalacionBarraAntiVuelco',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Barra AntiVuelco (Instalación)'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fechaInstalacionGps',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Gps (Instalación)'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fechaVencimientoLamina',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Lamina (Vencimiento)'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fechaVencimientoPermisoCirculacion',
            field=models.DateTimeField(null=True, verbose_name='Permiso Circulación (Vencimiento)'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fechaVencimientoRevisionTecnica',
            field=models.DateTimeField(null=True, verbose_name='Revisión Tecnica (Vencimiento)'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fechaVencimientoSeguroObligatorio',
            field=models.DateTimeField(null=True, verbose_name='Seguro Obligatorio (Vencimiento)'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fechaVencimientoTransportePrivado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Tranporte Privado (Vencimiento)'),
        ),
    ]
