# Generated by Django 5.0.1 on 2024-03-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0014_alter_vehiculo_fechainstalacionbarraantivuelco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='fechaVencimientoLamina',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Lámina (Vencimiento)'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fechaVencimientoRevisionTecnica',
            field=models.DateTimeField(null=True, verbose_name='Revisión Técnica (Vencimiento)'),
        ),
    ]
