# Generated by Django 5.0.1 on 2024-04-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0015_alter_vehiculo_fechavencimientolamina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='fechaArriendoFinal',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Arriendo Final'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fechaArriendoInicial',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Arriendo Inicial'),
        ),
    ]
