# Generated by Django 5.0.1 on 2024-04-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0016_vehiculo_fechaarriendofinal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tenencia',
            field=models.CharField(blank=True, choices=[('1', 'Propio'), ('2', 'Arrendado')], max_length=20, null=True, verbose_name='Tenencia'),
        ),
    ]
