# Generated by Django 5.0.1 on 2024-04-24 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0017_vehiculo_tenencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfraccionesVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Infracción')),
                ('infraccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Detalle Infraccion')),
                ('esatdoPago', models.BooleanField(null=True, verbose_name='Estado de Pago')),
                ('valor', models.IntegerField(blank=True, null=True, verbose_name='Valor')),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiculo')),
            ],
            options={
                'verbose_name': 'Información Infracción y Multas',
                'verbose_name_plural': 'Información Infraccionesy Multas',
                'db_table': 'vehicle_penalty',
            },
        ),
    ]
