# Generated by Django 5.0.1 on 2024-04-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0018_infraccionesvehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraccionesvehiculo',
            name='infraccion',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Detalle Infraccion'),
        ),
    ]
