# Generated by Django 5.0.1 on 2024-04-24 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0019_alter_infraccionesvehiculo_infraccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infraccionesvehiculo',
            old_name='esatdoPago',
            new_name='estadoPago',
        ),
    ]
