# Generated by Django 5.0.1 on 2024-04-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0020_rename_esatdopago_infraccionesvehiculo_estadopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraccionesvehiculo',
            name='ciudad',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ciudad / Lugar'),
        ),
    ]
