# Generated by Django 5.0.1 on 2024-04-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0021_infraccionesvehiculo_ciudad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infraccionesvehiculo',
            old_name='ciudad',
            new_name='ciudadInfraccion',
        ),
        migrations.RenameField(
            model_name='infraccionesvehiculo',
            old_name='estadoPago',
            new_name='estadoPagoInfraccion',
        ),
        migrations.RenameField(
            model_name='infraccionesvehiculo',
            old_name='fecha',
            new_name='fechaInfraccion',
        ),
        migrations.RenameField(
            model_name='infraccionesvehiculo',
            old_name='valor',
            new_name='valorInfraccion',
        ),
    ]
