# Generated by Django 5.0.1 on 2024-04-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0022_rename_ciudad_infraccionesvehiculo_ciudadinfraccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraccionesvehiculo',
            name='estadoPagoInfraccion',
            field=models.CharField(blank=True, choices=[('1', 'Pendiente'), ('2', 'Pagada'), ('2', 'Anulada')], max_length=10, null=True, verbose_name='Estado del Pago'),
        ),
    ]
