# Generated by Django 5.0.1 on 2024-04-24 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0023_alter_infraccionesvehiculo_estadopagoinfraccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraccionesvehiculo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiculo'),
        ),
    ]
