# Generated by Django 5.0.1 on 2024-05-23 04:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0024_alter_infraccionesvehiculo_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoKilometraje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometraje', models.IntegerField(blank=True, null=True, verbose_name='Kilometraje Actual')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiculo')),
            ],
            options={
                'verbose_name': 'Kilometraje Vehicular',
                'verbose_name_plural': 'Kilometrajes Vehicular',
                'db_table': 'vehicle_kilometres_registers',
            },
        ),
    ]
