# Generated by Django 5.0.1 on 2024-05-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0025_nuevokilometraje'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevokilometraje',
            name='origen',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Origen'),
        ),
    ]
