# Generated by Django 5.0.1 on 2024-05-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0026_nuevokilometraje_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='completado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Porcentaje de Completado'),
        ),
    ]
