# Generated by Django 5.0.1 on 2024-05-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0027_vehiculo_completado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='completado',
            field=models.IntegerField(blank=True, default=30, null=True, verbose_name='Porcentaje de Completado'),
        ),
    ]
