# Generated by Django 5.0.1 on 2024-05-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0029_informaciontecnicavehiculo_frecuenciamantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informaciontecnicavehiculo',
            name='frecuenciaMantenimiento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Frecuencia Mantenimiento(Kilometros)'),
        ),
    ]
