# Generated by Django 5.0.1 on 2024-05-27 06:39

import vehicle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0030_alter_informaciontecnicavehiculo_frecuenciamantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacionesvehiculo',
            name='fotografiaCertificadoGrua',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AddField(
            model_name='documentacionesvehiculo',
            name='fotografiaCertificadoMantencion',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
        migrations.AddField(
            model_name='documentacionesvehiculo',
            name='fotografiaCertificadoOperatividad',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre),
        ),
    ]
