# Generated by Django 5.0.1 on 2024-05-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0031_documentacionesvehiculo_fotografiacertificadogrua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informaciontecnicavehiculo',
            name='proximoMantenimiento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Próximo Mantenimiento(Kilometros)'),
        ),
        migrations.AddField(
            model_name='informaciontecnicavehiculo',
            name='proximoMantenimientoGrua',
            field=models.IntegerField(blank=True, null=True, verbose_name='Próximo Mantenimiento(Horómetro)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fechaCertificadoGrua',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Certificado Grúa'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fechaCertificadoMantencion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Certificado Mantención'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fechaCertificadoOperatividad',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Certificado Operatividad'),
        ),
    ]
