# Generated by Django 5.0.1 on 2024-06-01 09:00

import vehicle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0032_informaciontecnicavehiculo_proximomantenimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaCertificadoBarraAntiVuelco',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Certificado de Barra AntiVuelco'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaCertificadoGps',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Certificado GPS'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaCertificadoGrua',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Certificado de Grúa'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaCertificadoLamina',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Certificado de Lámina'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaCertificadoMantencion',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Certificado de Mantención'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaCertificadoOperatividad',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Certificado de Operatividad'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaCertificadoVarios',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Certificados Varios'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaDocumentacionMiniBus',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Documentación Transp. Privado'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaExteriorAtras',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen-vehiculo.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Fotografía Exterior Atrás'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaExteriorCopiloto',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen-vehiculo.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Fotografía Exterior Lado Acompañante'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaExteriorFrontis',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen-vehiculo.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Fotografía Exterior Frontis'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaExteriorPiloto',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen-vehiculo.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Fotografía Exterior Lado Conductor'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaFacturaCompra',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Factura de Compra'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaInteriorAtrasCopiloto',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen-vehiculo.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Fotografía Interior Atrás Acompañante'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaInteriorAtrasPiloto',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen-vehiculo.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Fotografía Interior Atrás Conductor'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaInteriorCopiloto',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen-vehiculo.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Fotografía Interior Acompañante'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaInteriorTablero',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen-vehiculo.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Fotografía Interior Tablero'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaPadron',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Padrón Vehicular'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaPermisoCirculacion',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Permiso de Circulación'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaRevisionTecnica',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Revisión Técnica'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaRevisionTecnicaGases',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Revisión Técnica de Gases'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaSeguroAutomotriz',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Seguro Automotriz'),
        ),
        migrations.AlterField(
            model_name='documentacionesvehiculo',
            name='fotografiaSeguroObligatorio',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Seguro Obligatorio'),
        ),
    ]
