# Generated by Django 5.0.1 on 2024-06-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0033_alter_documentacionesvehiculo_fotografiacertificadobarraantivuelco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraccionesvehiculo',
            name='estadoPagoInfraccion',
            field=models.CharField(blank=True, choices=[('1', 'Pendiente'), ('2', 'Pagada'), ('3', 'Anulada')], max_length=10, null=True, verbose_name='Estado del Pago'),
        ),
    ]
