# Generated by Django 5.1.1 on 2025-03-05 19:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0034_alter_infraccionesvehiculo_estadopagoinfraccion"),
    ]

    operations = [
        migrations.CreateModel(
            name="NuevaTarjetaCombustible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numeroTarjeta",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Número Tarjeta",
                    ),
                ),
                (
                    "patente",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Patente"
                    ),
                ),
                (
                    "tipoVehiculo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Tipo de Vehículo",
                    ),
                ),
                (
                    "nombrePropietario",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nombre Propietario",
                    ),
                ),
                (
                    "rutPropietario",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Rut Propietario",
                    ),
                ),
                (
                    "tipoDocumento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Factura"),
                            ("2", "Factura Exenta"),
                            ("3", "Boleta"),
                            ("4", "Guía Despacho"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Tipo Documento",
                    ),
                ),
                (
                    "tipoCombustible",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Diesel"),
                            ("2", "Gasolina 93"),
                            ("3", "Gasolina 95"),
                            ("4", "Gasolina 97"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Tipo Combustible",
                    ),
                ),
                (
                    "fechaVencimiento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Vencimiento"
                    ),
                ),
                (
                    "fechacreacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "faena",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Faena"
                    ),
                ),
                ("status", models.BooleanField(null=True, verbose_name="Estado")),
                (
                    "creador",
                    models.CharField(max_length=50, null=True, verbose_name="Creador"),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicle.vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarjeta de Combustible",
                "verbose_name_plural": "Tarjetas de Combustible",
                "db_table": "vehicle_fuel_cards",
            },
        ),
    ]
