# Generated by Django 5.1.5 on 2025-03-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0035_nuevatarjetacombustible'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevatarjetacombustible',
            name='actual',
            field=models.BooleanField(default=True, verbose_name='Registro Actual'),
        ),
        migrations.AlterField(
            model_name='nuevatarjetacombustible',
            name='numeroTarjeta',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Número Tarjeta'),
        ),
        migrations.AlterField(
            model_name='nuevatarjetacombustible',
            name='tipoCombustible',
            field=models.CharField(blank=True, choices=[('Diesel', 'Diesel'), ('Gasolina 93', 'Gasolina 93'), ('Gasolina 95', 'Gasolina 95'), ('Gasolina 97', 'Gasolina 97')], max_length=20, null=True, verbose_name='Tipo Combustible'),
        ),
        migrations.AlterField(
            model_name='nuevatarjetacombustible',
            name='tipoDocumento',
            field=models.CharField(blank=True, choices=[('Factura', 'Factura'), ('Factura Exenta', 'Factura Exenta'), ('Boleta', 'Boleta'), ('Guía Despacho', 'Guía Despacho')], max_length=20, null=True, verbose_name='Tipo Documento'),
        ),
    ]
