# Generated by Django 5.1.1 on 2025-03-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0036_nuevatarjetacombustible_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tarjetaCombustible',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tarjeta Combustible'),
        ),
    ]
