# Generated by Django 5.1.1 on 2025-03-11 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0037_vehiculo_tarjetacombustible'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaSomnolencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca Dispositivo')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Marca Dispositivo',
                'verbose_name_plural': 'Marcas Dispositivos',
                'db_table': 'vehicle sleepiness_brand',
            },
        ),
        migrations.CreateModel(
            name='ModeloSomnolencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo Dispositivo')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.marcasomnolencia')),
            ],
            options={
                'verbose_name': 'Modelo Dispositivo',
                'verbose_name_plural': 'Modelos Dispositivos',
                'db_table': 'vehicle sleepiness_model',
            },
        ),
        migrations.CreateModel(
            name='AyudaTecnicaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiculo')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.modelosomnolencia')),
            ],
            options={
                'verbose_name': 'Ayuda Técnica Vehículo',
                'verbose_name_plural': 'Ayudas Técnicas Vehículos',
                'db_table': 'vehicle_technical_helps',
            },
        ),
    ]
