# Generated by Django 5.1.1 on 2025-03-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0038_marcasomnolencia_modelosomnolencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayudatecnicavehiculo',
            name='dispositivo',
            field=models.BooleanField(null=True, verbose_name='¿Posee Dispositivo?'),
        ),
    ]
