# Generated by Django 5.1.1 on 2025-03-19 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0039_ayudatecnicavehiculo_dispositivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ayudatecnicavehiculo',
            name='modelo',
        ),
        migrations.AddField(
            model_name='ayudatecnicavehiculo',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.marcasomnolencia'),
        ),
        migrations.AlterField(
            model_name='marcasomnolencia',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='Proveedor Dispositivo'),
        ),
    ]
