# Generated by Django 5.1.1 on 2025-03-06 14:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(max_length=50, verbose_name="Categoría"),
                ),
                (
                    "creador",
                    models.CharField(max_length=50, null=True, verbose_name="Creador"),
                ),
                ("status", models.BooleanField(null=True, verbose_name="Estado")),
                (
                    "fechacreacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "db_table": "inventory_categoria_items",
            },
        ),
        migrations.CreateModel(
            name="DuracionItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duracion",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Duración",
                    ),
                ),
                (
                    "creador",
                    models.CharField(max_length=50, null=True, verbose_name="Creador"),
                ),
                ("status", models.BooleanField(null=True, verbose_name="Estado")),
                (
                    "fechacreacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Duración",
                "verbose_name_plural": "Duraciones",
                "db_table": "inventory_duracion_items",
            },
        ),
        migrations.CreateModel(
            name="SeccionItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seccion",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Sección"
                    ),
                ),
                (
                    "creador",
                    models.CharField(max_length=50, null=True, verbose_name="Creador"),
                ),
                ("status", models.BooleanField(null=True, verbose_name="Estado")),
                (
                    "fechacreacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Sección",
                "verbose_name_plural": "Secciones",
                "db_table": "inventory_seccion_items",
            },
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=250, verbose_name="Descripción"),
                ),
                (
                    "stock_minimo",
                    models.CharField(max_length=250, verbose_name="Stock Minimo"),
                ),
                (
                    "stock_maximo",
                    models.CharField(max_length=250, verbose_name="Stock Maximo"),
                ),
                ("status", models.BooleanField(null=True, verbose_name="Estado")),
                (
                    "fechacreacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.categoriaitems",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "duracion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.duracionitems",
                        verbose_name="Duración",
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.seccionitems",
                        verbose_name="Sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "db_table": "inventory_item_items",
            },
        ),
        migrations.AddField(
            model_name="categoriaitems",
            name="seccion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.seccionitems",
                verbose_name="Sección",
            ),
        ),
        migrations.CreateModel(
            name="StockEgresoItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faena", models.CharField(max_length=250, verbose_name="Faena")),
                (
                    "item",
                    models.CharField(max_length=250, unique=True, verbose_name="Item"),
                ),
                (
                    "movimiento",
                    models.CharField(max_length=250, verbose_name="Movimiento"),
                ),
                (
                    "cantidad",
                    models.IntegerField(default=0, verbose_name="Cantidad Stock"),
                ),
                (
                    "cantidad_entregada",
                    models.CharField(max_length=250, verbose_name="Cantidad Entregada"),
                ),
                (
                    "rut_receptor",
                    models.CharField(max_length=250, verbose_name="Rut Receptor"),
                ),
                (
                    "cargo_receptor",
                    models.CharField(max_length=250, verbose_name="Cargo Receptor"),
                ),
                (
                    "nombre_receptor",
                    models.CharField(max_length=250, verbose_name="Nombre Receptor"),
                ),
                (
                    "descripcion",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Observación"
                    ),
                ),
                (
                    "creador",
                    models.CharField(max_length=50, null=True, verbose_name="Creador"),
                ),
                (
                    "fechacreacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.categoriaitems",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.seccionitems",
                        verbose_name="Sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "StockEgresoItem",
                "verbose_name_plural": "StockEgresoItems",
                "db_table": "inventory_stockegresoitem_stockEgresoitems",
            },
        ),
        migrations.CreateModel(
            name="StockItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faena", models.CharField(max_length=250, verbose_name="Faena")),
                ("item", models.CharField(max_length=250, verbose_name="Item")),
                (
                    "movimiento",
                    models.CharField(max_length=250, verbose_name="Movimiento"),
                ),
                ("cantidad", models.IntegerField(default=0, verbose_name="Cantidad")),
                (
                    "descripcion",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Observación"
                    ),
                ),
                (
                    "creador",
                    models.CharField(max_length=50, null=True, verbose_name="Creador"),
                ),
                (
                    "fechacreacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.categoriaitems",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.seccionitems",
                        verbose_name="Sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "StockItem",
                "verbose_name_plural": "StockItems",
                "db_table": "inventory_stockitem_stockitems",
            },
        ),
    ]
