# Generated by Django 5.1.1 on 2025-03-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seccionitems",
            name="creador",
            field=models.CharField(max_length=50, null=True, verbose_name="Creador "),
        ),
        migrations.AlterField(
            model_name="seccionitems",
            name="seccion",
            field=models.CharField(max_length=50, unique=True, verbose_name="Sección "),
        ),
        migrations.AlterField(
            model_name="seccionitems",
            name="status",
            field=models.BooleanField(null=True, verbose_name="Estado "),
        ),
    ]
