# Generated by Django 5.1.1 on 2025-03-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_seccionitems_creador_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockegresoitems",
            name="cantidad_entregada",
            field=models.IntegerField(verbose_name="Cantidad Entregada"),
        ),
    ]
