# Generated by Django 5.1.1 on 2025-03-07 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_stockegresoitems_cantidad_entregada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockitems",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.items",
                verbose_name="Item",
            ),
        ),
    ]
