# Generated by Django 5.1.1 on 2025-03-07 21:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_stockitems_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockItemsHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faena", models.CharField(max_length=250, verbose_name="Faena")),
                (
                    "movimiento",
                    models.CharField(max_length=250, verbose_name="Movimiento"),
                ),
                ("cantidad", models.IntegerField(default=0, verbose_name="Cantidad")),
                (
                    "descripcion",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Observación"
                    ),
                ),
                (
                    "creador",
                    models.CharField(max_length=50, null=True, verbose_name="Creador"),
                ),
                (
                    "fechacreacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.categoriaitems",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.items",
                        verbose_name="Item",
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.seccionitems",
                        verbose_name="Sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "StockItemHistorico",
                "verbose_name_plural": "StockItemsHstoricos",
                "db_table": "inventory_stockitemhistorico_stockitemshistoricos",
            },
        ),
    ]
