# Generated by Django 5.1.1 on 2025-03-07 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_alter_recomendacion_azimut_alter_recomendacion_cota_and_more"),
        ("inventory", "0006_stockitemshistorico"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="faena",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.faena",
                verbose_name="Faena",
            ),
        ),
        migrations.AlterField(
            model_name="stockegresoitems",
            name="faena",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.faena",
                verbose_name="Faena",
            ),
        ),
        migrations.AlterField(
            model_name="stockitems",
            name="faena",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.faena",
                verbose_name="Faena",
            ),
        ),
        migrations.AlterField(
            model_name="stockitemshistorico",
            name="faena",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.faena",
                verbose_name="Faena",
            ),
        ),
    ]
