# Generated by Django 5.1.1 on 2025-03-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_items_faena_alter_stockegresoitems_faena_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitems",
            name="nueva_cantidad",
            field=models.IntegerField(default=0, verbose_name="Cantidad"),
        ),
    ]
