# Generated by Django 5.1.1 on 2025-03-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_stockitems_nueva_cantidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitems",
            name="unique",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Unique Hash"
            ),
        ),
    ]
