# Generated by Django 5.1.1 on 2025-03-07 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_stockitems_unique"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockitems",
            name="unique",
        ),
    ]
