# Generated by Django 5.1.1 on 2025-03-08 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_alter_recomendacion_azimut_alter_recomendacion_cota_and_more"),
        ("inventory", "0010_remove_stockitems_unique"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="items",
            unique_together={("faena", "seccion", "categoria", "item")},
        ),
    ]
