# Generated by Django 5.1.1 on 2025-03-08 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_alter_items_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="items",
            unique_together=set(),
        ),
    ]
