# Generated by Django 5.1.1 on 2025-03-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_alter_recomendacion_azimut_alter_recomendacion_cota_and_more"),
        ("inventory", "0012_alter_items_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="item",
            field=models.CharField(max_length=250, verbose_name="Nombre"),
        ),
        migrations.AlterUniqueTogether(
            name="items",
            unique_together={("faena", "seccion", "categoria", "item")},
        ),
    ]
