# Generated by Django 5.1.1 on 2025-03-08 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_alter_recomendacion_azimut_alter_recomendacion_cota_and_more"),
        ("inventory", "0013_alter_items_item_alter_items_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stockitems",
            unique_together={("faena", "seccion", "categoria", "item")},
        ),
    ]
