# Generated by Django 5.1.1 on 2025-03-12 19:03

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_alter_stockitems_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="imagen_item",
            field=models.ImageField(
                blank=True,
                default="inventario_item/no-imagen-item.png",
                null=True,
                upload_to=inventory.models.Items.generaNombre,
                verbose_name="Fotografía Item",
            ),
        ),
        migrations.AddField(
            model_name="items",
            name="marca",
            field=models.CharField(max_length=250, null=True, verbose_name="Marca"),
        ),
        migrations.AddField(
            model_name="items",
            name="valor_neto",
            field=models.IntegerField(null=True, verbose_name="Valor Neto"),
        ),
    ]
