# Generated by Django 5.1.1 on 2025-03-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_items_imagen_item_items_marca_items_valor_neto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockitems",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="stockitems",
            name="movimiento",
        ),
        migrations.RemoveField(
            model_name="stockitems",
            name="nueva_cantidad",
        ),
    ]
