# Generated by Django 5.1.1 on 2025-03-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_remove_stockitems_descripcion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitems",
            name="cantidad_actual",
            field=models.IntegerField(default=0, verbose_name="Cantidad Actual"),
        ),
    ]
