# Generated by Django 5.1.1 on 2025-03-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_stockitems_cantidad_actual"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitems",
            name="descripcion",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Observación"
            ),
        ),
    ]
