# Generated by Django 5.1.1 on 2025-03-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_stockitems_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitems",
            name="status",
            field=models.BooleanField(null=True, verbose_name="Estado"),
        ),
    ]
