# Generated by Django 5.1.1 on 2025-03-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_stockitems_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitemshistorico",
            name="cargo_receptor",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Cargo Receptor"
            ),
        ),
        migrations.AddField(
            model_name="stockitemshistorico",
            name="nombre_receptor",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Nombre Receptor"
            ),
        ),
        migrations.AddField(
            model_name="stockitemshistorico",
            name="rut_receptor",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Rut Receptor"
            ),
        ),
        migrations.AlterField(
            model_name="stockegresoitems",
            name="cargo_receptor",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Cargo Receptor"
            ),
        ),
        migrations.AlterField(
            model_name="stockegresoitems",
            name="nombre_receptor",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Nombre Receptor"
            ),
        ),
        migrations.AlterField(
            model_name="stockegresoitems",
            name="rut_receptor",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Rut Receptor"
            ),
        ),
    ]
