# Generated by Django 5.1.1 on 2025-03-12 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0020_stockitemshistorico_cargo_receptor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockitemshistorico",
            name="cargo_receptor",
        ),
        migrations.RemoveField(
            model_name="stockitemshistorico",
            name="nombre_receptor",
        ),
        migrations.RemoveField(
            model_name="stockitemshistorico",
            name="rut_receptor",
        ),
    ]
