# Generated by Django 5.1.1 on 2025-03-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_remove_stockitemshistorico_cargo_receptor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitemshistorico",
            name="cargo_receptor",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Cargo Receptor"
            ),
        ),
        migrations.AddField(
            model_name="stockitemshistorico",
            name="nombre_receptor",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Nombre Receptor"
            ),
        ),
        migrations.AddField(
            model_name="stockitemshistorico",
            name="rut_receptor",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Rut Receptor"
            ),
        ),
    ]
