# Generated by Django 5.1.1 on 2025-03-13 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_stockitemshistorico_cargo_receptor_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockegresoitems",
            old_name="cantidad_entregada",
            new_name="cantidad_actual",
        ),
    ]
