# Generated by Django 5.0.1 on 2024-05-02 07:36

import django.db.models.deletion
import django.utils.timezone
import machine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_rename_kitmaquinaina_fallamaquinaria_kitmaquinaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquinaria', models.CharField(max_length=50, unique=True, verbose_name='Código Maquinaria')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripción')),
                ('fechaAdquisicion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Adquisición')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fotografia', models.ImageField(blank=True, default='base/no-imagen.png', null=True, upload_to=machine.models.Maquinaria.generaNombre)),
                ('faena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faena', verbose_name='Modelo')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.marcamaquinaria', verbose_name='Marca')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipomaquinaria', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Maquinaria',
                'verbose_name_plural': 'Maquinarias',
                'db_table': 'machine_profile',
            },
        ),
    ]
