# Generated by Django 5.0.1 on 2024-05-03 05:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_kitmaquinaina_fallamaquinaria_kitmaquinaria'),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria',
            name='faena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faena', verbose_name='Faena'),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='maquinaria',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre Maquinaria'),
        ),
        migrations.CreateModel(
            name='MaquinariaFaena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('faena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faena', verbose_name='Faena')),
                ('maquinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.maquinaria', verbose_name='Maquinaria')),
            ],
            options={
                'verbose_name': 'Maquinaria Faena',
                'verbose_name_plural': 'Maquinarias Faenas',
                'db_table': 'mining_machines',
            },
        ),
    ]
