# Generated by Django 5.0.1 on 2024-05-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_alter_maquinaria_faena_alter_maquinaria_maquinaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='frecuenciaMantenimiento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Frecuencia Mantenimiento(Horas)'),
        ),
    ]
