# Generated by Django 5.0.1 on 2024-06-04 16:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_maquinaria_frecuenciamantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoHorometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horometro', models.IntegerField(blank=True, null=True, verbose_name='Horómetro Actual')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('origen', models.CharField(blank=True, max_length=30, null=True, verbose_name='Origen')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.maquinaria')),
            ],
            options={
                'verbose_name': 'Ho´rometro Maquinaria',
                'verbose_name_plural': 'Horómetros Maquinarias',
                'db_table': 'machine_horometres_registers',
            },
        ),
    ]
