# Generated by Django 5.0.1 on 2024-06-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_nuevohorometro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nuevohorometro',
            options={'verbose_name': 'Horómetro Maquinaria', 'verbose_name_plural': 'Horómetros Maquinarias'},
        ),
    ]
