# Generated by Django 5.0.1 on 2024-06-10 07:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_fechasimportantes_fechavencimiento'),
        ('machine', '0005_alter_nuevohorometro_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitsMaquinariaFaena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('faena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faena')),
                ('kitMaquinaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.kitsmaquinaria')),
            ],
            options={
                'verbose_name': 'Kit Maquinaria por Faena',
                'verbose_name_plural': 'Kits Maquinarias por Faenas',
                'db_table': 'machine_kits_machine_mining',
            },
        ),
        migrations.CreateModel(
            name='HistorialStockKitsMaquinariaFaena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockMovimiento', models.IntegerField(blank=True, null=True, verbose_name='Movimiento')),
                ('stockActual', models.IntegerField(blank=True, null=True, verbose_name='Stock Actual')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('faena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faena')),
                ('kitMaquinaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.kitsmaquinariafaena')),
            ],
            options={
                'verbose_name': 'Historial Stock Kit Maquinaria',
                'verbose_name_plural': 'Historial Stock Kits Maquinarias',
                'db_table': 'machine_kits_stock_history',
            },
        ),
        migrations.AddConstraint(
            model_name='kitsmaquinariafaena',
            constraint=models.UniqueConstraint(fields=('faena', 'kitMaquinaria'), name='unique_faena_kitMaquinaria'),
        ),
    ]
