# Generated by Django 5.0.1 on 2024-03-26 01:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_tipofallavehiculo'),
        ('user', '0002_documentacionusuario_fotografialicenciainterna_and_more'),
        ('vehicle', '0010_alter_informaciontecnicavehiculo_capacidadcarga_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevaSolicitudMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField(null=True, verbose_name='Telefono')),
                ('kilometraje', models.IntegerField(blank=True, null=True, verbose_name='Kilometraje')),
                ('turno', models.CharField(blank=True, choices=[('1', 'Turno A'), ('2', 'Turno B')], max_length=20, null=True, verbose_name='Turno')),
                ('comentario', models.CharField(max_length=1000, null=True, verbose_name='Comentarios Adiccionales')),
                ('avisoJefatura', models.BooleanField(null=True, verbose_name='Aviso a su Jefatura Directa?')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('patente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiculo', verbose_name='Patente Vehículo')),
                ('problemas', models.ManyToManyField(to='core.tipofallavehiculo')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usuario', verbose_name='Nombre Solicitante')),
            ],
            options={
                'verbose_name': 'Registro de Mantenimiento',
                'verbose_name_plural': 'Registros de Mantenimientos',
                'db_table': 'maintenance_register',
            },
        ),
    ]
