# Generated by Django 5.0.1 on 2024-03-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_nuevasolicitudmantenimiento_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevasolicitudmantenimiento',
            name='turno',
            field=models.CharField(blank=True, choices=[('2', 'Turno B'), ('1', 'Turno A')], max_length=20, null=True, verbose_name='Turno'),
        ),
    ]
