# Generated by Django 5.0.1 on 2024-03-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_nuevasolicitudmantenimiento_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuevasolicitudmantenimiento',
            name='problemas',
        ),
        migrations.AlterField(
            model_name='nuevasolicitudmantenimiento',
            name='turno',
            field=models.CharField(blank=True, choices=[('1', 'Turno A'), ('2', 'Turno B')], max_length=20, null=True, verbose_name='Turno'),
        ),
    ]
