# Generated by Django 5.0.1 on 2024-03-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_remove_nuevasolicitudmantenimiento_problemas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevasolicitudmantenimiento',
            name='avisoJefatura',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=20, null=True, verbose_name='Aviso a su Jefatura Directa?'),
        ),
    ]
