# Generated by Django 5.0.1 on 2024-03-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tipofallavehiculo'),
        ('maintenance', '0006_alter_nuevasolicitudmantenimiento_avisojefatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevasolicitudmantenimiento',
            name='problemas',
            field=models.ManyToManyField(to='core.tipofallavehiculo'),
        ),
        migrations.AlterField(
            model_name='nuevasolicitudmantenimiento',
            name='turno',
            field=models.CharField(blank=True, choices=[('2', 'Turno B'), ('1', 'Turno A')], max_length=20, null=True, verbose_name='Turno'),
        ),
    ]
