# Generated by Django 5.0.1 on 2024-03-26 03:18

import maintenance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_alter_nuevasolicitudmantenimiento_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevasolicitudmantenimiento',
            name='fotografiaDos',
            field=models.ImageField(blank=True, default='base/no-imagen2.png', null=True, upload_to=maintenance.models.NuevaSolicitudMantenimiento.generaNombre),
        ),
        migrations.AddField(
            model_name='nuevasolicitudmantenimiento',
            name='fotografiaTres',
            field=models.ImageField(blank=True, default='base/no-imagen2.png', null=True, upload_to=maintenance.models.NuevaSolicitudMantenimiento.generaNombre),
        ),
        migrations.AddField(
            model_name='nuevasolicitudmantenimiento',
            name='fotografiaUno',
            field=models.ImageField(blank=True, default='base/no-imagen2.png', null=True, upload_to=maintenance.models.NuevaSolicitudMantenimiento.generaNombre),
        ),
        migrations.AlterField(
            model_name='nuevasolicitudmantenimiento',
            name='turno',
            field=models.CharField(blank=True, choices=[('2', 'Turno B'), ('1', 'Turno A')], max_length=20, null=True, verbose_name='Turno'),
        ),
    ]
