# Generated by Django 5.0.1 on 2024-03-26 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_nuevasolicitudmantenimiento_fotografiados_and_more'),
        ('user', '0002_documentacionusuario_fotografialicenciainterna_and_more'),
        ('vehicle', '0010_alter_informaciontecnicavehiculo_capacidadcarga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevasolicitudmantenimiento',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiculo', verbose_name='Vehículo ID'),
        ),
        migrations.AlterField(
            model_name='nuevasolicitudmantenimiento',
            name='patente',
            field=models.CharField(max_length=50, null=True, verbose_name='Patente'),
        ),
        migrations.AlterField(
            model_name='nuevasolicitudmantenimiento',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usuario', verbose_name='Usuario ID'),
        ),
    ]
