# Generated by Django 5.0.1 on 2024-03-26 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_nuevasolicitudmantenimiento_vehiculo_and_more'),
        ('user', '0002_documentacionusuario_fotografialicenciainterna_and_more'),
        ('vehicle', '0010_alter_informaciontecnicavehiculo_capacidadcarga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevasolicitudmantenimiento',
            name='comentario',
            field=models.CharField(max_length=1000, null=True, verbose_name='Comentarios Adicionales'),
        ),
        migrations.AlterField(
            model_name='nuevasolicitudmantenimiento',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usuario', verbose_name='Nombre Usuario'),
        ),
        migrations.AlterField(
            model_name='nuevasolicitudmantenimiento',
            name='turno',
            field=models.CharField(blank=True, choices=[('1', 'Turno A'), ('2', 'Turno B')], max_length=20, null=True, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='nuevasolicitudmantenimiento',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiculo', verbose_name='Patente'),
        ),
    ]
