# Generated by Django 5.0.1 on 2024-03-28 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_ano_ano_alter_color_color_and_more'),
        ('maintenance', '0012_nuevasolicitudmantenimiento_faena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevasolicitudmantenimiento',
            name='faena',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faena', verbose_name='Faena'),
        ),
    ]
