# Generated by Django 5.0.1 on 2024-04-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_alter_nuevasolicitudmantenimiento_faena'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevasolicitudmantenimiento',
            name='progreso',
            field=models.CharField(blank=True, choices=[('1', 'Solicitud'), ('2', 'En Mantención'), ('3', 'Terminada'), ('4', 'Anulada')], default='Solicitud', max_length=50, null=True, verbose_name='Progreso Solicitud'),
        ),
    ]
