# Generated by Django 5.0.1 on 2024-04-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_nuevasolicitudmantenimiento_progreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevasolicitudmantenimiento',
            name='progreso',
            field=models.CharField(blank=True, choices=[('1', 'Solicitud'), ('2', 'En Mantención'), ('3', 'Terminada'), ('4', 'Anulada')], default=1, max_length=50, null=True, verbose_name='Progreso Solicitud'),
        ),
    ]
