# Generated by Django 5.0.1 on 2024-04-04 04:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_alter_nuevasolicitudmantenimiento_progreso'),
        ('user', '0002_documentacionusuario_fotografialicenciainterna_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialSolicitudMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso', models.CharField(blank=True, choices=[('1', 'Solicitud'), ('2', 'En Mantención'), ('3', 'Terminada'), ('4', 'Anulada')], max_length=50, null=True, verbose_name='Progreso')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usuario', verbose_name='Nombre Usuario')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.nuevasolicitudmantenimiento', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Historial Registro de Mantenimiento',
                'verbose_name_plural': 'Historial Registros de Mantenimientos',
                'db_table': 'maintenance_register_history',
            },
        ),
    ]
