# Generated by Django 5.0.1 on 2024-04-25 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_documento_tipodocumentofaenageneral_archivodocumento_and_more'),
        ('maintenance', '0016_historialsolicitudmantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudMantenimientoProblemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorServicio', models.IntegerField(blank=True, null=True, verbose_name='Valor Servicio')),
                ('descripcion', models.CharField(max_length=100, null=True, verbose_name='Descripción')),
                ('fallaVehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipofallavehiculo', verbose_name='Falla Vehiculo')),
                ('solicitudMantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.nuevasolicitudmantenimiento', verbose_name='Solicitud Mantenimiento')),
            ],
        ),
        migrations.AlterField(
            model_name='nuevasolicitudmantenimiento',
            name='problemas',
            field=models.ManyToManyField(through='maintenance.SolicitudMantenimientoProblemas', to='core.tipofallavehiculo'),
        ),
    ]
