# Generated by Django 5.0.1 on 2024-04-25 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_documento_tipodocumentofaenageneral_archivodocumento_and_more'),
        ('maintenance', '0017_solicitudmantenimientoproblemas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialsolicitudmantenimiento',
            name='empresaMantenimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresaservicios', verbose_name='Empresa Servicios'),
        ),
    ]
