# Generated by Django 5.0.1 on 2024-04-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0019_nuevasolicitudmantenimiento_empresamantenimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialsolicitudmantenimiento',
            name='progreso',
            field=models.CharField(blank=True, choices=[('1', 'Solicitud'), ('2', 'En Mantención'), ('3', 'Segunda Revisión'), ('4', 'Terminada'), ('5', 'Anulada')], max_length=50, null=True, verbose_name='Progreso Solicitud'),
        ),
        migrations.AlterField(
            model_name='nuevasolicitudmantenimiento',
            name='progreso',
            field=models.CharField(blank=True, choices=[('1', 'Solicitud'), ('2', 'En Mantención'), ('3', 'Segunda Revisión'), ('4', 'Terminada'), ('5', 'Anulada')], default=1, max_length=50, null=True, verbose_name='Progreso Solicitud'),
        ),
    ]
