# Generated by Django 5.0.1 on 2024-05-08 19:00

import django.db.models.deletion
import django.utils.timezone
import maintenance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_kitmaquinaina_fallamaquinaria_kitmaquinaria'),
        ('machine', '0002_alter_maquinaria_faena_alter_maquinaria_maquinaria_and_more'),
        ('maintenance', '0020_alter_historialsolicitudmantenimiento_progreso_and_more'),
        ('user', '0003_usuarioprofile_faena_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevaSolicitudMantenimientoMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField(null=True, verbose_name='Telefono')),
                ('horometro', models.IntegerField(blank=True, null=True, verbose_name='Horómetro')),
                ('progreso', models.CharField(blank=True, choices=[('1', 'Solicitud'), ('2', 'En Mantención'), ('3', 'Segunda Revisión'), ('4', 'Terminada'), ('5', 'Anulada')], default=1, max_length=50, null=True, verbose_name='Progreso Solicitud')),
                ('turno', models.CharField(blank=True, choices=[('1', 'Turno A'), ('2', 'Turno B')], max_length=20, null=True, verbose_name='Turno')),
                ('comentario', models.CharField(max_length=1000, null=True, verbose_name='Comentarios Adicionales')),
                ('avisoJefatura', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=20, null=True, verbose_name='Aviso a su Jefatura Directa?')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fotografiaUno', models.ImageField(blank=True, default='base/no-imagen2.png', null=True, upload_to=maintenance.models.NuevaSolicitudMantenimientoMaquinaria.generaNombre)),
                ('fotografiaDos', models.ImageField(blank=True, default='base/no-imagen2.png', null=True, upload_to=maintenance.models.NuevaSolicitudMantenimientoMaquinaria.generaNombre)),
                ('empresaMantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresaservicios', verbose_name='Empresa Servicios')),
                ('faena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faena', verbose_name='Faena')),
                ('maquinaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.maquinaria', verbose_name='Nombre Maquinaria')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usuario', verbose_name='Nombre Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Mantenimiento Maquinaria',
                'verbose_name_plural': 'Registros de Mantenimientos Maquinarias',
                'db_table': 'maintenance_register_machines',
            },
        ),
        migrations.CreateModel(
            name='HistorialSolicitudMantenimientoMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso', models.CharField(blank=True, choices=[('1', 'Solicitud'), ('2', 'En Mantención'), ('3', 'Segunda Revisión'), ('4', 'Terminada'), ('5', 'Anulada')], max_length=50, null=True, verbose_name='Progreso Solicitud')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresaMantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresaservicios', verbose_name='Empresa Servicios')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usuario', verbose_name='Nombre Usuario')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.nuevasolicitudmantenimientomaquinaria', verbose_name='Solicitud Maquinaria')),
            ],
            options={
                'verbose_name': 'Historial Registro de Mantenimiento Maquinaria',
                'verbose_name_plural': 'Historial Registros de Mantenimientos Maquinarias',
                'db_table': 'maintenance_register_history_machines',
            },
        ),
        migrations.CreateModel(
            name='SolicitudMantenimientoProblemasMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorServicio', models.IntegerField(blank=True, null=True, verbose_name='Valor Servicio')),
                ('descripcion', models.CharField(max_length=100, null=True, verbose_name='Descripción')),
                ('fallaMaquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fallamaquinaria', verbose_name='Falla Maquinaria')),
                ('solicitudMantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.nuevasolicitudmantenimientomaquinaria', verbose_name='Solicitud Mantenimiento')),
            ],
        ),
        migrations.AddField(
            model_name='nuevasolicitudmantenimientomaquinaria',
            name='problemas',
            field=models.ManyToManyField(through='maintenance.SolicitudMantenimientoProblemasMaquinaria', to='core.fallamaquinaria'),
        ),
    ]
