# Generated by Django 5.0.1 on 2024-07-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0021_nuevasolicitudmantenimientomaquinaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso', models.CharField(choices=[('1', 'Solicitud'), ('2', 'En Mantención'), ('3', 'Segunda Revisión'), ('4', 'Terminada'), ('5', 'Anulada')], max_length=1)),
            ],
        ),
    ]
