# Generated by Django 5.0.1 on 2024-09-11 10:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0033_aditivos_cantidadagua_casing_corona_and_more'),
        ('user', '0005_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportesOperacionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('1', 'Turno A'), ('2', 'Turno B')], max_length=50, verbose_name='Turno')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('sondajeSerie', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(3940), django.core.validators.MaxValueValidator(4400)], verbose_name='Serie')),
                ('sondajeEstado', models.CharField(max_length=2, null=True, verbose_name='Estado')),
                ('metroInicial', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Metro Inicial')),
                ('metroFinal', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Metro Final')),
                ('totalPerforado', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total Perforado')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('controlador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usuario', verbose_name='Controlador')),
                ('perforista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.perforistas', verbose_name='Perforista')),
                ('sonda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sondas', verbose_name='Sonda')),
                ('sondajeCodigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sondajes', verbose_name='Sondaje')),
            ],
            options={
                'verbose_name': 'Reporte Digital Operacional',
                'verbose_name_plural': 'Reportes Digitales Operacionales',
                'db_table': 'drilling_reporte_digital_operacional',
            },
        ),
        migrations.CreateModel(
            name='ObservacionesReportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(max_length=1000, null=True, verbose_name='Observaciones')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drilling.reportesoperacionales')),
            ],
            options={
                'verbose_name': 'Reporte Digital Observacion',
                'verbose_name_plural': 'Reportes Digitales Observaciones',
                'db_table': 'drilling_reporte_digital_observaciones',
            },
        ),
        migrations.CreateModel(
            name='LongitudPozos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largoBarril', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(5.5)], verbose_name='Largo del Barril (mts)')),
                ('puntoMuerto', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Punto Muerto (mts)')),
                ('restoBarra', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Resto de Barra (mts)')),
                ('numeroBarras', models.IntegerField(verbose_name='Numero de Barras')),
                ('longitudPozo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Longitud Pozo (mts)')),
                ('largoBarra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.largobarra', verbose_name='Largo Barra (mts)')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drilling.reportesoperacionales')),
            ],
            options={
                'verbose_name': 'Reporte Digital Longitud',
                'verbose_name_plural': 'Reportes Digitales Longitud',
                'db_table': 'drilling_reporte_digital_longitud',
            },
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corona', models.CharField(max_length=50, null=True, verbose_name='Corona')),
                ('escareador', models.CharField(max_length=50, null=True, verbose_name='Escariador')),
                ('casing', models.CharField(max_length=50, null=True, verbose_name='Casing')),
                ('zapata', models.CharField(max_length=50, null=True, verbose_name='Zapata')),
                ('cantidadAgua', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cantidadagua', verbose_name='Agua (lts)')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drilling.reportesoperacionales')),
            ],
            options={
                'verbose_name': 'Reporte Digital Insumo',
                'verbose_name_plural': 'Reportes Digitales Insumos',
                'db_table': 'drilling_reporte_digital_insumos',
            },
        ),
        migrations.CreateModel(
            name='DetallesPerforaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perforado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('desde', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hasta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recuperacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentajeRecuperacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('barra', models.IntegerField()),
                ('totalHtas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diametros', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.diametros')),
                ('orientacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.orientacion')),
                ('tipoTerreno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipoterreno')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drilling.reportesoperacionales')),
            ],
            options={
                'verbose_name': 'Reporte Digital Perforación',
                'verbose_name_plural': 'Reportes Digitales Perforaciones',
                'db_table': 'drilling_reporte_digital_perforaciones',
            },
        ),
        migrations.CreateModel(
            name='ControlesHorarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField()),
                ('inicio', models.TimeField(verbose_name='Hora Inicio')),
                ('final', models.TimeField(verbose_name='Hora final')),
                ('total', models.TimeField(verbose_name='Total Horas')),
                ('detalleControlHorario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.detallecontrolhorario', verbose_name='Detalle Control Horario')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drilling.reportesoperacionales')),
            ],
            options={
                'verbose_name': 'Reporte Digital Control Horario',
                'verbose_name_plural': 'Reportes Digitales Control Horario',
                'db_table': 'drilling_reporte_digital_control_horario',
            },
        ),
        migrations.CreateModel(
            name='Aditivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Cantidad')),
                ('aditivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aditivos', verbose_name='Aditivos')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drilling.reportesoperacionales')),
            ],
            options={
                'verbose_name': 'Reporte Digital Aditivo',
                'verbose_name_plural': 'Reportes Digitales Aditivos',
                'db_table': 'drilling_reporte_digital_aditivos',
            },
        ),
    ]
