# Generated by Django 5.0.1 on 2024-09-11 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesperforaciones',
            name='fechacreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
