# Generated by Django 5.0.1 on 2024-09-16 03:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0002_detallesperforaciones_fechacreacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aditivos',
            name='fechacreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='controleshorarios',
            name='fechacreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
