# Generated by Django 5.0.1 on 2024-09-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_aditivos_cantidadagua_casing_corona_and_more'),
        ('drilling', '0003_aditivos_fechacreacion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aditivos',
            new_name='DetalleAditivos',
        ),
    ]
