# Generated by Django 5.0.1 on 2024-09-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0004_rename_aditivos_detalleaditivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportesoperacionales',
            name='progreso',
            field=models.CharField(default='Creado', max_length=50, null=True, verbose_name='Progreso'),
        ),
    ]
