# Generated by Django 5.0.1 on 2024-09-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0005_reportesoperacionales_progreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleshorarios',
            name='status',
            field=models.BooleanField(null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='detalleaditivos',
            name='status',
            field=models.BooleanField(null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='detallesperforaciones',
            name='status',
            field=models.BooleanField(null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='insumos',
            name='status',
            field=models.BooleanField(null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='longitudpozos',
            name='status',
            field=models.BooleanField(null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='observacionesreportes',
            name='status',
            field=models.BooleanField(null=True, verbose_name='Estado'),
        ),
    ]
