# Generated by Django 5.1.1 on 2024-10-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0006_controleshorarios_status_detalleaditivos_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportesoperacionales',
            name='sondajeEstado',
            field=models.CharField(choices=[('1', 'A'), ('2', 'B')], max_length=3, null=True, verbose_name='Gemelo'),
        ),
    ]
