# Generated by Django 5.1.1 on 2024-10-15 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0007_alter_reportesoperacionales_sondajeestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longitudpozos',
            name='largoBarra',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9.0)], verbose_name='Largo Barra (mts)'),
        ),
    ]
