# Generated by Django 5.1.1 on 2024-10-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0008_alter_longitudpozos_largobarra'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportesoperacionales',
            name='correlativo',
            field=models.IntegerField(null=True, verbose_name='Correlativo'),
        ),
    ]
