# Generated by Django 5.1.1 on 2024-10-16 03:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0009_reportesoperacionales_correlativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportesoperacionales',
            name='fechaedicion',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
