# Generated by Django 5.1.1 on 2024-10-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0010_reportesoperacionales_fechaedicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesperforaciones',
            name='largoBarra',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
