# Generated by Django 5.1.1 on 2024-11-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0011_detallesperforaciones_largobarra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportesoperacionales',
            name='sondajeEstado',
            field=models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B')], max_length=3, null=True, verbose_name='Gemelo'),
        ),
    ]
