# Generated by Django 5.1.1 on 2024-11-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0012_alter_reportesoperacionales_sondajeestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportesoperacionales',
            name='sondajeEstado',
            field=models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B')], default='', max_length=3, null=True, verbose_name='Gemelo'),
        ),
    ]
