# Generated by Django 5.1.1 on 2024-11-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0013_alter_reportesoperacionales_sondajeestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportesoperacionales',
            name='id_checklist',
            field=models.IntegerField(null=True, verbose_name='ID Checklist'),
        ),
    ]
