# Generated by Django 5.1.1 on 2024-11-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0014_reportesoperacionales_id_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='longitudpozos',
            name='htaEnPozo',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=50, null=True, verbose_name='Hta. en el Pozo'),
        ),
        migrations.AddField(
            model_name='longitudpozos',
            name='mtsDeHta',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Mts. de Hta.'),
        ),
        migrations.AddField(
            model_name='longitudpozos',
            name='profundidadHta',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Profundidad ala que queda (mts)'),
        ),
    ]
