# Generated by Django 5.1.1 on 2024-12-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0015_longitudpozos_htaenpozo_longitudpozos_mtsdehta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportesoperacionales',
            name='id_checklist',
            field=models.BigIntegerField(null=True, verbose_name='ID Checklist'),
        ),
    ]
