# Generated by Django 5.1.1 on 2024-12-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0016_alter_reportesoperacionales_id_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longitudpozos',
            name='htaEnPozo',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=50, verbose_name='Hta. en el Pozo'),
        ),
    ]
