# Generated by Django 5.1.1 on 2025-04-03 04:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0019_alter_longitudpozos_htaenpozo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosReportesPerforaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporte', models.CharField(max_length=200, verbose_name='Tipo Reporte')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('archivo', models.FileField(upload_to='archivos/')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Documento Reporte Perforacion',
                'verbose_name_plural': 'Documentos Reportes Perforaciones',
                'db_table': 'drilling_documents_report_drilling',
            },
        ),
    ]
