# Generated by Django 5.1.1 on 2025-04-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0020_documentosreportesperforaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosreportesperforaciones',
            name='archivo',
            field=models.FileField(upload_to='reportes_avance_campaña/'),
        ),
    ]
