# Generated by Django 5.1.1 on 2025-04-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0021_alter_documentosreportesperforaciones_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosreportesperforaciones',
            name='archivo',
            field=models.FileField(upload_to='reportes_avance/'),
        ),
    ]
