# Generated by Django 5.0.1 on 2024-02-24 00:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('CONDUCTOR', 'Conductor'), ('TRABAJADOR', 'Trabajador'), ('SIN ASIGNAR', 'Sin Asignar')], max_length=50, verbose_name='Rol')),
                ('phone', models.IntegerField(null=True, unique=True, verbose_name='Telefono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
            managers=[
                ('Usuario', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografiaUsuario', models.ImageField(blank=True, default='documentacion_usuario/no-avatar.png', null=True, upload_to=user.models.DocumentacionUsuario.generaNombre)),
                ('fotografiaCedula', models.ImageField(blank=True, default='documentacion_usuario/no-imagen.png', null=True, upload_to=user.models.DocumentacionUsuario.generaNombre)),
                ('fotografiaLicencia', models.ImageField(blank=True, default='documentacion_usuario/no-imagen.png', null=True, upload_to=user.models.DocumentacionUsuario.generaNombre)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documentacion Usuario',
                'verbose_name_plural': 'Documentacion Usuarios',
                'db_table': 'user_documentacion',
            },
        ),
        migrations.CreateModel(
            name='LicenciasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaLicenciaVencimiento', models.DateTimeField(null=True, verbose_name='Licencia Conducir (Vencimiento)')),
                ('licenciaClaseB', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='Clase B')),
                ('licenciaClaseC', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='Clase C')),
                ('licenciaClaseD', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='Clase D')),
                ('licenciaClaseE', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='Clase E')),
                ('licenciaClaseF', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='Clase F')),
                ('licenciaClaseA1', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='Clase A1')),
                ('licenciaClaseA2', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='Clase A2')),
                ('licenciaClaseA3', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='Clase A3')),
                ('licenciaClaseA4', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='Clase A4')),
                ('licenciaClaseA5', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='Clase A5')),
                ('licenciaClaseA1Antigua', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='Clase A1 Antigua')),
                ('licenciaClaseA2Antigua', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='Clase A2 Antigua')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Licencia de Conducir',
                'verbose_name_plural': 'Licencia de Conducir',
                'db_table': 'user_licencia_conducir',
            },
        ),
        migrations.CreateModel(
            name='UsuarioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNacimiento', models.DateTimeField(null=True, verbose_name='Fecha Nacimiento')),
                ('fechaCedulaVencimiento', models.DateTimeField(null=True, verbose_name='Cédula Identidad (Vencimiento)')),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ciudad', verbose_name='Ciudad')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.genero', verbose_name='Genero')),
                ('nacionalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.nacionalidad', verbose_name='Nacionalidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Información Adicional',
                'verbose_name_plural': 'Usuarios Información Adicional',
            },
        ),
    ]
