# Generated by Django 5.0.1 on 2024-03-07 12:23

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacionusuario',
            name='fotografiaLicenciaInterna',
            field=models.ImageField(blank=True, default='documentacion_usuario/no-imagen.png', null=True, upload_to=user.models.DocumentacionUsuario.generaNombre),
        ),
        migrations.AddField(
            model_name='licenciasusuario',
            name='fechaLicenciaInternaVencimiento',
            field=models.DateTimeField(null=True, verbose_name='Licencia Interna (Vencimiento)'),
        ),
    ]
