# Generated by Django 5.0.1 on 2024-04-24 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_categoriafallavehiculo_categoria'),
        ('user', '0002_documentacionusuario_fotografialicenciainterna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioprofile',
            name='faena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faena', verbose_name='Faena'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('JEFE MANTENCION', 'Jefe Mantencion'), ('SUPERVISOR', 'Supervisor'), ('CONDUCTOR', 'Conductor'), ('TRABAJADOR', 'Trabajador'), ('SIN ASIGNAR', 'Sin Asignar')], max_length=50, verbose_name='Rol'),
        ),
    ]
