# Generated by Django 5.0.1 on 2024-08-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usuarioprofile_faena_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioprofile',
            name='seccionPrevencion',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=10, null=True, verbose_name='Sección Prevención de Riesgos'),
        ),
        migrations.AddField(
            model_name='usuarioprofile',
            name='seccionSondaje',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=10, null=True, verbose_name='Sección Sondaje'),
        ),
        migrations.AddField(
            model_name='usuarioprofile',
            name='seccionVehicular',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=10, null=True, verbose_name='Sección Vehicular'),
        ),
    ]
