# Generated by Django 5.0.1 on 2024-09-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usuarioprofile_seccionprevencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('JEFE MANTENCION', 'Jefe Mantencion'), ('SUPERVISOR', 'Supervisor'), ('CONTROLADOR', 'Controlador'), ('PERFORISTA', 'Perforista'), ('CONDUCTOR', 'Conductor'), ('TRABAJADOR', 'Trabajador'), ('SIN ASIGNAR', 'Sin Asignar')], max_length=50, verbose_name='Rol'),
        ),
    ]
