# Generated by Django 5.1.1 on 2024-10-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('JEFE MANTENCION', 'Jefe Mantencion'), ('SUPERVISOR', 'Supervisor'), ('CONTROLADOR', 'Controlador'), ('BASE DATOS', 'Base de Datos'), ('CONDUCTOR', 'Conductor'), ('TRABAJADOR', 'Trabajador'), ('SIN ASIGNAR', 'Sin Asignar')], max_length=50, verbose_name='Rol'),
        ),
    ]
