# Generated by Django 5.1.1 on 2025-02-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarioprofile",
            name="seccionInventario",
            field=models.CharField(
                blank=True,
                choices=[("Si", "Si"), ("No", "No")],
                default="No",
                max_length=10,
                null=True,
                verbose_name="Sección Inventario",
            ),
        ),
    ]
